export const apiCates = [
  {
    name: 'charts',
    items: [
      'AreaChart',
      'BarChart',
      'LineChart',
      'ComposedChart',
      'PieChart',
      'RadarChart',
      'RadialBarChart',
      'ScatterChart',
      'FunnelChart',
      'Treemap',
      'Sankey',
      'SunburstChart',
    ],
  },
  {
    name: 'general-components',
    items: [
      'ResponsiveContainer',
      'Legend',
      'DefaultLegendContent',
      'Tooltip',
      'DefaultTooltipContent',
      'useIsTooltipActive',
      'useActiveTooltipCoordinate',
      'useActiveTooltipDataPoints',
      'useActiveTooltipLabel',
      'Cell',
      'Text',
      'Label',
      'LabelList',
      'Layer',
      'Customized',
      'ZIndexLayer',
      'DefaultZIndexes',
      'Surface',
      'useMargin',
      'useOffset',
      'usePlotArea',
      'useChartWidth',
      'useChartHeight',
      'getNiceTickValues',
      'Global',
      'getChartPointer',
    ],
  },
  {
    name: 'cartesian-components',
    items: [
      'Area',
      'Bar',
      'BarStack',
      'Line',
      'Scatter',
      'XAxis',
      'useXAxisDomain',
      'YAxis',
      'useYAxisDomain',
      'ZAxis',
      'Brush',
      'CartesianAxis',
      'CartesianGrid',
      'ReferenceLine',
      'ReferenceDot',
      'ReferenceArea',
      'ErrorBar',
      'Funnel',
    ],
  },
  {
    name: 'polar-components',
    items: ['Pie', 'Radar', 'RadialBar', 'PolarAngleAxis', 'PolarGrid', 'PolarRadiusAxis'],
  },
  {
    name: 'shapes',
    items: ['Cross', 'Curve', 'Dot', 'Polygon', 'Rectangle', 'Sector', 'Trapezoid', 'Symbols'],
  },
];
