export const apiCates = [
  {
    name: 'charts',
    items: [
      'AreaChart',
      'BarChart',
      'LineChart',
      'ComposedChart',
      'PieChart',
      'RadarChart',
      'RadialBarChart',
      'ScatterChart',
      'FunnelChart',
      'Treemap',
      'Sankey',
    ],
  },
  {
    name: 'general-components',
    items: [
      'ResponsiveContainer',
      'Legend',
      'DefaultLegendContent',
      'Tooltip',
      'DefaultTooltipContent',
      'Cell',
      'Text',
      'Label',
      'LabelList',
      'Layer',
      'Customized',
      'ZIndexLayer',
    ],
  },
  {
    name: 'cartesian-components',
    items: [
      'Area',
      'Bar',
      'BarStack',
      'Line',
      'Scatter',
      'XAxis',
      'YAxis',
      'ZAxis',
      'Brush',
      'CartesianAxis',
      'CartesianGrid',
      'ReferenceLine',
      'ReferenceDot',
      'ReferenceArea',
      'ErrorBar',
      'Funnel',
    ],
  },
  {
    name: 'polar-components',
    items: ['Pie', 'Radar', 'RadialBar', 'PolarAngleAxis', 'PolarGrid', 'PolarRadiusAxis'],
  },
  {
    name: 'shapes',
    items: ['Cross', 'Curve', 'Dot', 'Polygon', 'Rectangle', 'Sector', 'Trapezoid'],
  },
];
