/**
 * This file is auto-generated by generateStorybookArgsFromSource.ts
 * Do not edit manually.
 */
import { StorybookArgs } from '../../../StorybookArgs';

export const AreaArgs: StorybookArgs = {
  activeDot: {
    description:
      'The dot is shown when user enter an area chart and this chart has tooltip.\nIf false set, no active dot will not be drawn.\nIf true set, active dot will be drawn which have the props calculated internally.\nIf object set, active dot will be drawn which have the props merged by the internal calculated props and the option.\nIf ReactElement set, the option can be the custom active dot element.\nIf set a function, the function will be called to render customized active dot.',
    table: {
      type: {
        summary: 'false | true | Function | Partial<ActiveDotProps> | ReactNode',
      },
      category: 'General',
      defaultValue: {
        summary: 'true',
      },
    },
    defaultValue: true,
  },
  animationBegin: {
    description: 'Specifies when the animation should begin, the unit of this option is ms.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'Animation',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  animationDuration: {
    description: 'Specifies the duration of animation, the unit of this option is ms.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'Animation',
      defaultValue: {
        summary: '1500',
      },
    },
    defaultValue: 1500,
  },
  animationEasing: {
    description: 'The type of easing function.',
    control: {
      type: 'select',
    },
    options: ['linear', 'ease', 'ease-in', 'ease-out', 'ease-in-out'],
    table: {
      type: {
        summary: '"linear" | "ease" | "ease-in" | "ease-out" | "ease-in-out"',
      },
      category: 'Animation',
      defaultValue: {
        summary: 'ease',
      },
    },
    defaultValue: 'ease',
  },
  baseLine: {
    description:
      'Baseline of the area:\n- number: uses the corresponding axis value as a flat baseline;\n- an array of coordinates: describes a custom baseline path.',
    table: {
      type: {
        summary: 'number | Array<readonly NullableCoordinate>',
      },
      category: 'General',
    },
  },
  baseValue: {
    table: {
      type: {
        summary: 'number | "dataMin" | "dataMax"',
      },
      category: 'General',
    },
  },
  children: {
    table: {
      type: {
        summary: 'ReactNode',
      },
      category: 'General',
    },
  },
  className: {
    control: {
      type: 'text',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'Style',
    },
  },
  connectNulls: {
    description: 'Whether to connect the curve across null points.',
    control: {
      type: 'boolean',
    },
    table: {
      type: {
        summary: 'boolean',
      },
      category: 'General',
      defaultValue: {
        summary: 'false',
      },
    },
    defaultValue: false,
  },
  data: {
    table: {
      type: {
        summary: 'Array<unknown>',
      },
      category: 'General',
    },
  },
  dataKey: {
    description:
      'Decides how to extract the value of this Area from the data:\n- `string`: the name of the field in the data object;\n- `number`: the index of the field in the data;\n- `function`: a function that receives the data object and returns the value of this Area.\n\nIf undefined, it will reuse the dataKey of YAxis.',
    table: {
      type: {
        summary: 'string | number | Function',
      },
      category: 'General',
    },
  },
  dot: {
    description:
      'If false set, dots will not be drawn.\nIf true set, dots will be drawn which have the props calculated internally.\nIf object set, dots will be drawn which have the props merged by the internal calculated props and the option.\nIf ReactElement set, the option can be the custom dot element.\nIf set a function, the function will be called to render customized dot.',
    table: {
      type: {
        summary: 'false | true | Function | Partial<Props> | ReactNode',
      },
      category: 'General',
      defaultValue: {
        summary: 'false',
      },
    },
    defaultValue: false,
  },
  hide: {
    description:
      'Hides the whole graphical element when true.\n\nHiding an element is different from removing it from the chart:\nHidden graphical elements are still visible in Legend,\nand can be included in axis domain calculations,\ndepending on `includeHidden` props of your XAxis/YAxis.',
    control: {
      type: 'boolean',
    },
    table: {
      type: {
        summary: 'boolean',
      },
      category: 'General',
      defaultValue: {
        summary: 'false',
      },
    },
    defaultValue: false,
  },
  id: {
    description:
      'Unique identifier of this component.\nUsed as an HTML attribute `id`, and also to identify this element internally.\n\nIf undefined, Recharts will generate a unique ID automatically.',
    control: {
      type: 'text',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'General',
    },
  },
  isAnimationActive: {
    description:
      'If set false, animation of area will be disabled.\nIf set "auto", the animation will be disabled in SSR and enabled in browser.',
    table: {
      type: {
        summary: 'false | true | "auto"',
      },
      category: 'Animation',
      defaultValue: {
        summary: 'auto',
      },
    },
    defaultValue: 'auto',
  },
  isRange: {
    control: {
      type: 'boolean',
    },
    table: {
      type: {
        summary: 'boolean',
      },
      category: 'General',
    },
  },
  label: {
    description:
      'Renders one label for each data point. Options:\n\n- `true`: renders default labels\n- `false`: no labels are rendered\n- `object`: the props of LabelList component\n- `ReactElement`: a custom label element\n- `function`: a render function of custom label',
    table: {
      type: {
        summary: 'false | true | ReactNode | Function | Props',
      },
      category: 'General',
      defaultValue: {
        summary: 'false',
      },
    },
    defaultValue: false,
  },
  legendType: {
    description: "The type of icon in legend.\nIf set to 'none', no legend item will be rendered.",
    control: {
      type: 'select',
    },
    options: ['none', 'circle', 'cross', 'diamond', 'line', 'plainline', 'rect', 'square', 'star', 'triangle', 'wye'],
    table: {
      type: {
        summary:
          '"none" | "circle" | "cross" | "diamond" | "line" | "plainline" | "rect" | "square" | "star" | "triangle" | "wye"',
      },
      category: 'General',
      defaultValue: {
        summary: 'line',
      },
    },
    defaultValue: 'line',
  },
  name: {
    description:
      'The name of data.\nThis option will be used in tooltip and legend to represent this graphical item.\nIf no value was set to this option, the value of dataKey will be used alternatively.',
    control: {
      type: 'text',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'General',
    },
  },
  onAbort: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAbortCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationEnd: {
    description: 'The customized event handler of animation end',
    table: {
      type: {
        summary: 'AnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationEndCapture: {
    table: {
      type: {
        summary: 'AnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationIteration: {
    table: {
      type: {
        summary: 'AnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationIterationCapture: {
    table: {
      type: {
        summary: 'AnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationStart: {
    description: 'The customized event handler of animation start',
    table: {
      type: {
        summary: 'AnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationStartCapture: {
    table: {
      type: {
        summary: 'AnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAuxClick: {
    table: {
      type: {
        summary: 'RechartsMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAuxClickCapture: {
    table: {
      type: {
        summary: 'RechartsMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onBeforeInput: {
    table: {
      type: {
        summary: 'FormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onBeforeInputCapture: {
    table: {
      type: {
        summary: 'FormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onBlur: {
    table: {
      type: {
        summary: 'FocusEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onBlurCapture: {
    table: {
      type: {
        summary: 'FocusEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCanPlay: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCanPlayCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCanPlayThrough: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCanPlayThroughCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onChange: {
    table: {
      type: {
        summary: 'FormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onChangeCapture: {
    table: {
      type: {
        summary: 'FormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onClick: {
    description: 'The customized event handler of click on the curve',
    table: {
      type: {
        summary: 'CurveMouseEventHandler',
      },
      category: 'Events',
    },
  },
  onClickCapture: {
    table: {
      type: {
        summary: 'RechartsMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionEnd: {
    table: {
      type: {
        summary: 'CompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionEndCapture: {
    table: {
      type: {
        summary: 'CompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionStart: {
    table: {
      type: {
        summary: 'CompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionStartCapture: {
    table: {
      type: {
        summary: 'CompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionUpdate: {
    table: {
      type: {
        summary: 'CompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionUpdateCapture: {
    table: {
      type: {
        summary: 'CompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onContextMenu: {
    table: {
      type: {
        summary: 'RechartsMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onContextMenuCapture: {
    table: {
      type: {
        summary: 'RechartsMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCopy: {
    table: {
      type: {
        summary: 'ClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCopyCapture: {
    table: {
      type: {
        summary: 'ClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCut: {
    table: {
      type: {
        summary: 'ClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCutCapture: {
    table: {
      type: {
        summary: 'ClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDoubleClick: {
    table: {
      type: {
        summary: 'RechartsMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDoubleClickCapture: {
    table: {
      type: {
        summary: 'RechartsMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDrag: {
    table: {
      type: {
        summary: 'DragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragCapture: {
    table: {
      type: {
        summary: 'DragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragEnd: {
    table: {
      type: {
        summary: 'DragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragEndCapture: {
    table: {
      type: {
        summary: 'DragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragEnter: {
    table: {
      type: {
        summary: 'DragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragEnterCapture: {
    table: {
      type: {
        summary: 'DragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragExit: {
    table: {
      type: {
        summary: 'DragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragExitCapture: {
    table: {
      type: {
        summary: 'DragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragLeave: {
    table: {
      type: {
        summary: 'DragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragLeaveCapture: {
    table: {
      type: {
        summary: 'DragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragOver: {
    table: {
      type: {
        summary: 'DragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragOverCapture: {
    table: {
      type: {
        summary: 'DragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragStart: {
    table: {
      type: {
        summary: 'DragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragStartCapture: {
    table: {
      type: {
        summary: 'DragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDrop: {
    table: {
      type: {
        summary: 'DragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDropCapture: {
    table: {
      type: {
        summary: 'DragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDurationChange: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDurationChangeCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEmptied: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEmptiedCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEncrypted: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEncryptedCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEnded: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEndedCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onError: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onErrorCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onFocus: {
    table: {
      type: {
        summary: 'FocusEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onFocusCapture: {
    table: {
      type: {
        summary: 'FocusEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onGotPointerCapture: {
    table: {
      type: {
        summary: 'PointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onGotPointerCaptureCapture: {
    table: {
      type: {
        summary: 'PointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onInput: {
    table: {
      type: {
        summary: 'FormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onInputCapture: {
    table: {
      type: {
        summary: 'FormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onInvalid: {
    table: {
      type: {
        summary: 'FormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onInvalidCapture: {
    table: {
      type: {
        summary: 'FormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyDown: {
    table: {
      type: {
        summary: 'KeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyDownCapture: {
    table: {
      type: {
        summary: 'KeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyPress: {
    table: {
      type: {
        summary: 'KeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyPressCapture: {
    table: {
      type: {
        summary: 'KeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyUp: {
    table: {
      type: {
        summary: 'KeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyUpCapture: {
    table: {
      type: {
        summary: 'KeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoad: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadedData: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadedDataCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadedMetadata: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadedMetadataCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadStart: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadStartCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLostPointerCapture: {
    table: {
      type: {
        summary: 'PointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLostPointerCaptureCapture: {
    table: {
      type: {
        summary: 'PointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseDown: {
    description: 'The customized event handler of mousedown on the curve',
    table: {
      type: {
        summary: 'CurveMouseEventHandler',
      },
      category: 'Events',
    },
  },
  onMouseDownCapture: {
    table: {
      type: {
        summary: 'RechartsMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseEnter: {
    description: 'The customized event handler of mouseenter on the curve',
    table: {
      type: {
        summary: 'CurveMouseEventHandler',
      },
      category: 'Events',
    },
  },
  onMouseLeave: {
    description: 'The customized event handler of mouseleave on the curve',
    table: {
      type: {
        summary: 'CurveMouseEventHandler',
      },
      category: 'Events',
    },
  },
  onMouseMove: {
    description: 'The customized event handler of mousemove on the curve',
    table: {
      type: {
        summary: 'CurveMouseEventHandler',
      },
      category: 'Events',
    },
  },
  onMouseMoveCapture: {
    table: {
      type: {
        summary: 'RechartsMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseOut: {
    description: 'The customized event handler of mouseout on the curve',
    table: {
      type: {
        summary: 'CurveMouseEventHandler',
      },
      category: 'Events',
    },
  },
  onMouseOutCapture: {
    table: {
      type: {
        summary: 'RechartsMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseOver: {
    description: 'The customized event handler of mouseover on the curve',
    table: {
      type: {
        summary: 'CurveMouseEventHandler',
      },
      category: 'Events',
    },
  },
  onMouseOverCapture: {
    table: {
      type: {
        summary: 'RechartsMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseUp: {
    description: 'The customized event handler of mouseup on the curve',
    table: {
      type: {
        summary: 'CurveMouseEventHandler',
      },
      category: 'Events',
    },
  },
  onMouseUpCapture: {
    table: {
      type: {
        summary: 'RechartsMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPaste: {
    table: {
      type: {
        summary: 'ClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPasteCapture: {
    table: {
      type: {
        summary: 'ClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPause: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPauseCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPlay: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPlayCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPlaying: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPlayingCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerCancel: {
    table: {
      type: {
        summary: 'PointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerCancelCapture: {
    table: {
      type: {
        summary: 'PointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerDown: {
    table: {
      type: {
        summary: 'PointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerDownCapture: {
    table: {
      type: {
        summary: 'PointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerEnter: {
    table: {
      type: {
        summary: 'PointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerEnterCapture: {
    table: {
      type: {
        summary: 'PointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerLeave: {
    table: {
      type: {
        summary: 'PointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerLeaveCapture: {
    table: {
      type: {
        summary: 'PointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerMove: {
    table: {
      type: {
        summary: 'PointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerMoveCapture: {
    table: {
      type: {
        summary: 'PointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerOut: {
    table: {
      type: {
        summary: 'PointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerOutCapture: {
    table: {
      type: {
        summary: 'PointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerOver: {
    table: {
      type: {
        summary: 'PointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerOverCapture: {
    table: {
      type: {
        summary: 'PointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerUp: {
    table: {
      type: {
        summary: 'PointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerUpCapture: {
    table: {
      type: {
        summary: 'PointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onProgress: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onProgressCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onRateChange: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onRateChangeCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onReset: {
    table: {
      type: {
        summary: 'FormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onResetCapture: {
    table: {
      type: {
        summary: 'FormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onScroll: {
    table: {
      type: {
        summary: 'UIEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onScrollCapture: {
    table: {
      type: {
        summary: 'UIEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSeeked: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSeekedCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSeeking: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSeekingCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSelect: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSelectCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onStalled: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onStalledCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSubmit: {
    table: {
      type: {
        summary: 'FormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSubmitCapture: {
    table: {
      type: {
        summary: 'FormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSuspend: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSuspendCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTimeUpdate: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTimeUpdateCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchCancel: {
    table: {
      type: {
        summary: 'TouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchCancelCapture: {
    table: {
      type: {
        summary: 'TouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchEnd: {
    table: {
      type: {
        summary: 'TouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchEndCapture: {
    table: {
      type: {
        summary: 'TouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchMove: {
    table: {
      type: {
        summary: 'TouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchMoveCapture: {
    table: {
      type: {
        summary: 'TouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchStart: {
    table: {
      type: {
        summary: 'TouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchStartCapture: {
    table: {
      type: {
        summary: 'TouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTransitionEnd: {
    table: {
      type: {
        summary: 'TransitionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTransitionEndCapture: {
    table: {
      type: {
        summary: 'TransitionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onVolumeChange: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onVolumeChangeCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onWaiting: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onWaitingCapture: {
    table: {
      type: {
        summary: 'ReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onWheel: {
    table: {
      type: {
        summary: 'WheelEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onWheelCapture: {
    table: {
      type: {
        summary: 'WheelEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  stackId: {
    description: 'When two Areas have the same axisId and same stackId, then the two Areas are stacked in the chart.',
    table: {
      type: {
        summary: 'string | number',
      },
      category: 'General',
    },
  },
  stroke: {
    description: 'The stroke color. If "none", no line will be drawn.',
    control: {
      type: 'color',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'Style',
      defaultValue: {
        summary: '#3182bd',
      },
    },
    defaultValue: '#3182bd',
  },
  strokeDasharray: {
    description: 'The pattern of dashes and gaps used to paint the line.',
    table: {
      type: {
        summary: 'string | number',
      },
      category: 'Style',
    },
  },
  strokeWidth: {
    description: 'The width of the stroke',
    table: {
      type: {
        summary: 'string | number',
      },
      category: 'Style',
      defaultValue: {
        summary: '1',
      },
    },
    defaultValue: 1,
  },
  tooltipType: {
    table: {
      type: {
        summary: '"none"',
      },
      category: 'General',
    },
  },
  type: {
    description: 'The interpolation type of curve. Allows custom interpolation function.',
    table: {
      type: {
        summary:
          '"step" | "basis" | "basisClosed" | "basisOpen" | "bumpX" | "bumpY" | "bump" | "linear" | "linearClosed" | "natural" | "monotoneX" | "monotoneY" | "monotone" | "stepBefore" | "stepAfter" | CurveFactory',
      },
      category: 'General',
      defaultValue: {
        summary: 'linear',
      },
    },
    defaultValue: 'linear',
  },
  unit: {
    description: 'The unit of data. This option will be used in tooltip.',
    table: {
      type: {
        summary: 'string | number',
      },
      category: 'General',
    },
  },
  xAxisId: {
    description: 'The id of XAxis which is corresponding to the data. Required when there are multiple XAxes.',
    table: {
      type: {
        summary: 'string | number',
      },
      category: 'General',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  yAxisId: {
    description: 'The id of YAxis which is corresponding to the data. Required when there are multiple YAxes.',
    table: {
      type: {
        summary: 'string | number',
      },
      category: 'General',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  zIndex: {
    description:
      'Z-Index of this component and its children. The higher the value,\nthe more on top it will be rendered.\nComponents with higher zIndex will appear in front of components with lower zIndex.\nIf undefined or 0, the content is rendered in the default layer without portals.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
      defaultValue: {
        summary: '100',
      },
    },
    defaultValue: 100,
  },
};
