/**
 * This file is auto-generated by generateStorybookArgsFromSource.ts
 * Do not edit manually.
 */
import { StorybookArgs } from '../../../StorybookArgs';

export const BarArgs: StorybookArgs = {
  activeBar: {
    description:
      'The active bar is shown when a user enters a bar chart and this chart has tooltip. Options:\n- `false`: all bars are passive, nothing happens on mouse events;\n- `true`: active bar is rendered separately but the default props are the same as others: so mouse events do not change its appearance. className and zIndex are different though;\n- `object`: the props of active bar;\n- `function`: the render function of active bar;\n- `ReactElement`: the active bar element.',
    table: {
      type: {
        summary: '(union of 5 variants)',
      },
      category: 'General',
      defaultValue: {
        summary: 'false',
      },
    },
    defaultValue: false,
  },
  animationBegin: {
    description: 'Specifies when the animation should begin, the unit of this option is ms.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'Animation',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  animationDuration: {
    description: 'Specifies the duration of animation, the unit of this option is ms.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'Animation',
      defaultValue: {
        summary: '400',
      },
    },
    defaultValue: 400,
  },
  animationEasing: {
    description: 'The type of easing function.',
    table: {
      type: {
        summary: '(union of 9 variants)',
      },
      category: 'Animation',
      defaultValue: {
        summary: 'ease',
      },
    },
    defaultValue: 'ease',
  },
  background: {
    description:
      'Renders a background for each bar. Options:\n - `false`: no background;\n - `true`: renders default background;\n - `object`: the props of background rectangle;\n - `ReactElement`: a custom background element;\n - `function`: a render function of custom background.',
    table: {
      type: {
        summary: '(union of 5 variants)',
      },
      category: 'General',
      defaultValue: {
        summary: 'false',
      },
    },
    defaultValue: false,
  },
  barSize: {
    description:
      'The width or height of each bar. If the barSize is not specified, the size of bar will be calculated by the barCategoryGap, barGap and the quantity of bar groups.',
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  children: {
    table: {
      type: {
        summary: 'ReactNode',
      },
      category: 'General',
    },
  },
  className: {
    control: {
      type: 'text',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'Style',
    },
  },
  dangerouslySetInnerHTML: {
    table: {
      type: {
        summary: 'Object',
      },
      category: 'General',
    },
  },
  dataKey: {
    description:
      'Decides how to extract the value of this Bar from the data:\n- `string`: the name of the field in the data object;\n- `number`: the index of the field in the data;\n- `function`: a function that receives the data object and returns the value of this Bar.',
    table: {
      type: {
        summary: 'Function | number | string',
      },
      category: 'General',
    },
  },
  hide: {
    description:
      'Hides the whole graphical element when true.\n\nHiding an element is different from removing it from the chart:\nHidden graphical elements are still visible in Legend,\nand can be included in axis domain calculations,\ndepending on `includeHidden` props of your XAxis/YAxis.',
    control: {
      type: 'boolean',
    },
    table: {
      type: {
        summary: 'boolean',
      },
      category: 'General',
      defaultValue: {
        summary: 'false',
      },
    },
    defaultValue: false,
  },
  id: {
    description:
      'The unique identifier of this component.\nUsed as an HTML attribute `id`, and also to identify this element internally.\n\nIf undefined, Recharts will generate a unique ID automatically.',
    control: {
      type: 'text',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'General',
    },
  },
  index: {
    table: {
      type: {
        summary: 'bigint | number | string',
      },
      category: 'General',
    },
  },
  isAnimationActive: {
    description:
      'If set false, animation of bar will be disabled.\nIf set "auto", the animation will be disabled in SSR and enabled in browser.',
    table: {
      type: {
        summary: '"auto" | false | true',
      },
      category: 'Animation',
      defaultValue: {
        summary: 'auto',
      },
    },
    defaultValue: 'auto',
  },
  label: {
    description:
      'Renders one label for each bar. Options:\n- `true`: renders default labels;\n- `false`: no labels are rendered;\n- `object`: the props of LabelList component;\n- `ReactElement`: a custom label element;\n- `function`: a render function of custom label.',
    table: {
      type: {
        summary: 'Function | Props | ReactNode | false | true',
      },
      category: 'General',
      defaultValue: {
        summary: 'false',
      },
    },
    defaultValue: false,
  },
  legendType: {
    description: "The type of icon in legend. If set to 'none', no legend item will be rendered.",
    control: {
      type: 'select',
    },
    options: ['none', 'circle', 'cross', 'diamond', 'line', 'plainline', 'rect', 'square', 'star', 'triangle', 'wye'],
    table: {
      type: {
        summary:
          '"circle" | "cross" | "diamond" | "line" | "none" | "plainline" | "rect" | "square" | "star" | "triangle" | "wye"',
      },
      category: 'General',
      defaultValue: {
        summary: 'rect',
      },
    },
    defaultValue: 'rect',
  },
  maxBarSize: {
    description: 'The maximum width of bar in a horizontal chart, or maximum height in a vertical chart.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
    },
  },
  minPointSize: {
    description:
      'The minimal height of a bar in a horizontal chart, or the minimal width of a bar in a vertical chart.\n\nBy default, 0 values are not shown.\nTo visualize a 0 (or close to zero) point, set the minimal point size to a pixel value like 3.\n\nIn stacked bar charts, minPointSize might not be respected for tightly packed values.\nSo we strongly recommend not using this props in stacked BarChart.\n\nYou may provide a function to conditionally change this prop based on Bar value.',
    table: {
      type: {
        summary: 'Function | number',
      },
      category: 'General',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  name: {
    description:
      'The name of data.\nThis option will be used in tooltip and legend to represent a bar.\nIf no value was set to this option, the value of dataKey will be used alternatively.',
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  onAbort: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAbortCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationEnd: {
    description: 'The customized event handler of animation end',
    table: {
      type: {
        summary: 'Function',
      },
      category: 'Events',
    },
  },
  onAnimationEndCapture: {
    table: {
      type: {
        summary: 'AdaptChildAnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationIteration: {
    table: {
      type: {
        summary: 'AdaptChildAnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationIterationCapture: {
    table: {
      type: {
        summary: 'AdaptChildAnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationStart: {
    description: 'The customized event handler of animation start',
    table: {
      type: {
        summary: 'Function',
      },
      category: 'Events',
    },
  },
  onAnimationStartCapture: {
    table: {
      type: {
        summary: 'AdaptChildAnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAuxClick: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAuxClickCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onBeforeInput: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onBeforeInputCapture: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onBlur: {
    table: {
      type: {
        summary: 'AdaptChildFocusEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onBlurCapture: {
    table: {
      type: {
        summary: 'AdaptChildFocusEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCanPlay: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCanPlayCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCanPlayThrough: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCanPlayThroughCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onChange: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onChangeCapture: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onClick: {
    description: 'The customized event handler of click on the bars in this group',
    table: {
      type: {
        summary: 'BarMouseEvent',
      },
      category: 'Events',
    },
  },
  onClickCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionEnd: {
    table: {
      type: {
        summary: 'AdaptChildCompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionEndCapture: {
    table: {
      type: {
        summary: 'AdaptChildCompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionStart: {
    table: {
      type: {
        summary: 'AdaptChildCompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionStartCapture: {
    table: {
      type: {
        summary: 'AdaptChildCompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionUpdate: {
    table: {
      type: {
        summary: 'AdaptChildCompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionUpdateCapture: {
    table: {
      type: {
        summary: 'AdaptChildCompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onContextMenu: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onContextMenuCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCopy: {
    table: {
      type: {
        summary: 'AdaptChildClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCopyCapture: {
    table: {
      type: {
        summary: 'AdaptChildClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCut: {
    table: {
      type: {
        summary: 'AdaptChildClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCutCapture: {
    table: {
      type: {
        summary: 'AdaptChildClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDoubleClick: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDoubleClickCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDrag: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragEnd: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragEndCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragEnter: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragEnterCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragExit: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragExitCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragLeave: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragLeaveCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragOver: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragOverCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragStart: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragStartCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDrop: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDropCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDurationChange: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDurationChangeCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEmptied: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEmptiedCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEncrypted: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEncryptedCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEnded: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEndedCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onError: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onErrorCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onFocus: {
    table: {
      type: {
        summary: 'AdaptChildFocusEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onFocusCapture: {
    table: {
      type: {
        summary: 'AdaptChildFocusEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onGotPointerCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onGotPointerCaptureCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onInput: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onInputCapture: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onInvalid: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onInvalidCapture: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyDown: {
    table: {
      type: {
        summary: 'AdaptChildKeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyDownCapture: {
    table: {
      type: {
        summary: 'AdaptChildKeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyPress: {
    table: {
      type: {
        summary: 'AdaptChildKeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyPressCapture: {
    table: {
      type: {
        summary: 'AdaptChildKeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyUp: {
    table: {
      type: {
        summary: 'AdaptChildKeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyUpCapture: {
    table: {
      type: {
        summary: 'AdaptChildKeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoad: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadedData: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadedDataCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadedMetadata: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadedMetadataCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadStart: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadStartCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLostPointerCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLostPointerCaptureCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseDown: {
    description: 'The customized event handler of mousedown on the bars in this group',
    table: {
      type: {
        summary: 'BarMouseEvent',
      },
      category: 'Events',
    },
  },
  onMouseDownCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseEnter: {
    description: 'The customized event handler of mouseenter on the bars in this group',
    table: {
      type: {
        summary: 'BarMouseEvent',
      },
      category: 'Events',
    },
  },
  onMouseLeave: {
    description: 'The customized event handler of mouseleave on the bars in this group',
    table: {
      type: {
        summary: 'BarMouseEvent',
      },
      category: 'Events',
    },
  },
  onMouseMove: {
    description: 'The customized event handler of mousemove on the bars in this group',
    table: {
      type: {
        summary: 'BarMouseEvent',
      },
      category: 'Events',
    },
  },
  onMouseMoveCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseOut: {
    description: 'The customized event handler of mouseout on the bars in this group',
    table: {
      type: {
        summary: 'BarMouseEvent',
      },
      category: 'Events',
    },
  },
  onMouseOutCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseOver: {
    description: 'The customized event handler of mouseover on the bars in this group',
    table: {
      type: {
        summary: 'BarMouseEvent',
      },
      category: 'Events',
    },
  },
  onMouseOverCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseUp: {
    description: 'The customized event handler of mouseup on the bars in this group',
    table: {
      type: {
        summary: 'BarMouseEvent',
      },
      category: 'Events',
    },
  },
  onMouseUpCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPaste: {
    table: {
      type: {
        summary: 'AdaptChildClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPasteCapture: {
    table: {
      type: {
        summary: 'AdaptChildClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPause: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPauseCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPlay: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPlayCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPlaying: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPlayingCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerCancel: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerCancelCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerDown: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerDownCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerEnter: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerEnterCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerLeave: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerLeaveCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerMove: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerMoveCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerOut: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerOutCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerOver: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerOverCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerUp: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerUpCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onProgress: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onProgressCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onRateChange: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onRateChangeCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onReset: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onResetCapture: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onScroll: {
    table: {
      type: {
        summary: 'AdaptChildUIEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onScrollCapture: {
    table: {
      type: {
        summary: 'AdaptChildUIEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSeeked: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSeekedCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSeeking: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSeekingCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSelect: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSelectCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onStalled: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onStalledCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSubmit: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSubmitCapture: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSuspend: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSuspendCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTimeUpdate: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTimeUpdateCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchCancel: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchCancelCapture: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchEnd: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchEndCapture: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchMove: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchMoveCapture: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchStart: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchStartCapture: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTransitionEnd: {
    table: {
      type: {
        summary: 'AdaptChildTransitionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTransitionEndCapture: {
    table: {
      type: {
        summary: 'AdaptChildTransitionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onVolumeChange: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onVolumeChangeCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onWaiting: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onWaitingCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onWheel: {
    table: {
      type: {
        summary: 'AdaptChildWheelEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onWheelCapture: {
    table: {
      type: {
        summary: 'AdaptChildWheelEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  radius: {
    description:
      'The radius of corners.\n\nIf you provide a single number, it applies to all four corners.\nIf you provide an array of four numbers, they apply to top-left, top-right, bottom-right, bottom-left corners respectively.',
    table: {
      type: {
        summary: '[number, number, number, number] | number',
      },
      category: 'General',
    },
  },
  shape: {
    description:
      'If set a ReactElement, the shape of bar can be customized.\nIf set a function, the function will be called to render customized shape.\nBy default, renders a rectangle.',
    table: {
      type: {
        summary: '(union of 5 variants)',
      },
      category: 'General',
    },
  },
  stackId: {
    description: 'When two Bars have the same axisId and same stackId, then the two Bars are stacked in the chart.',
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  tooltipType: {
    table: {
      type: {
        summary: '"none"',
      },
      category: 'General',
    },
  },
  unit: {
    description: 'The unit of data. This option will be used in tooltip.',
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  xAxisId: {
    description: 'The id of XAxis which is corresponding to the data. Required when there are multiple XAxes.',
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  yAxisId: {
    description: 'The id of YAxis which is corresponding to the data. Required when there are multiple YAxes.',
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  zIndex: {
    description:
      'Z-Index of this component and its children. The higher the value,\nthe more on top it will be rendered.\nComponents with higher zIndex will appear in front of components with lower zIndex.\nIf undefined or 0, the content is rendered in the default layer without portals.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
      defaultValue: {
        summary: '300',
      },
    },
    defaultValue: 300,
  },
};
