/**
 * This file is auto-generated by generateStorybookArgsFromSource.ts
 * Do not edit manually.
 */
import { StorybookArgs } from '../../../StorybookArgs';

export const BrushArgs: StorybookArgs = {
  alwaysShowText: {
    control: {
      type: 'boolean',
    },
    table: {
      type: {
        summary: 'boolean',
      },
      category: 'General',
      defaultValue: {
        summary: 'false',
      },
    },
    defaultValue: false,
  },
  ariaLabel: {
    control: {
      type: 'text',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'General',
    },
  },
  children: {
    table: {
      type: {
        summary: 'ReactNode',
      },
      category: 'General',
    },
  },
  className: {
    control: {
      type: 'text',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'Style',
    },
  },
  dataKey: {
    description:
      'Decides how to extract the value of this Brush from the data:\n- `string`: the name of the field in the data object;\n- `number`: the index of the field in the data;\n- `function`: a function that receives the data object and returns the value of this Brush.',
    table: {
      type: {
        summary: 'Function | number | string',
      },
      category: 'General',
    },
  },
  dy: {
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  endIndex: {
    description:
      'The default end index of brush.\nIf the option is not set, the end index will be calculated by the length of data.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
    },
  },
  gap: {
    description: 'Number of data points to skip between chart refreshes.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
      defaultValue: {
        summary: '1',
      },
    },
    defaultValue: 1,
  },
  height: {
    description: 'Height of the brush in pixels.',
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
      defaultValue: {
        summary: '40',
      },
    },
    defaultValue: 40,
  },
  leaveTimeOut: {
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
      defaultValue: {
        summary: '1000',
      },
    },
    defaultValue: 1000,
  },
  onChange: {
    description: 'The handler of changing the active scope of brush.',
    table: {
      type: {
        summary: 'OnBrushUpdate',
      },
      category: 'Events',
    },
  },
  onDragEnd: {
    table: {
      type: {
        summary: 'OnBrushUpdate',
      },
      category: 'Events',
    },
  },
  padding: {
    table: {
      type: {
        summary: 'Padding',
      },
      category: 'General',
      defaultValue: {
        summary: '{"top":1,"right":1,"bottom":1,"left":1}',
      },
    },
    defaultValue: {
      top: 1,
      right: 1,
      bottom: 1,
      left: 1,
    },
  },
  startIndex: {
    description: 'The default start index of brush.\nIf the option is not set, the start index will be 0.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
    },
  },
  tickFormatter: {
    description: 'The formatter function of ticks.',
    table: {
      type: {
        summary: 'BrushTickFormatter',
      },
      category: 'General',
    },
  },
  traveller: {
    table: {
      type: {
        summary: 'Function | ReactNode',
      },
      category: 'General',
    },
  },
  travellerWidth: {
    description: 'The width of each traveller.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
      defaultValue: {
        summary: '5',
      },
    },
    defaultValue: 5,
  },
  width: {
    description: 'Width of the brush in pixels.\nIf undefined, defaults to the chart width.',
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  x: {
    description:
      "The x-coordinate of brush.\nIf left undefined, it will be computed from the chart's offset and margins.",
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  y: {
    description:
      "The y-coordinate of brush.\nIf left undefined, it will be computed from the chart's offset and margins.",
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
};
