/**
 * This file is auto-generated by generateStorybookArgsFromSource.ts
 * Do not edit manually.
 */
import { StorybookArgs } from '../../../StorybookArgs';

export const CartesianGridArgs: StorybookArgs = {
  fill: {
    description: 'The background color used to fill the space between grid lines',
    control: {
      type: 'color',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'Style',
      defaultValue: {
        summary: 'none',
      },
    },
    defaultValue: 'none',
  },
  fillOpacity: {
    description: 'The opacity of the background used to fill the space between grid lines',
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  height: {
    description: 'The height of grid. If undefined, covers the full height of the chart plot area.',
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  horizontal: {
    description: 'If set false, no horizontal grid lines will be drawn.',
    table: {
      type: {
        summary: '(union of 5 variants)',
      },
      category: 'General',
      defaultValue: {
        summary: 'true',
      },
    },
    defaultValue: true,
  },
  horizontalCoordinatesGenerator: {
    description: 'A function that generates the y-coordinates of all horizontal lines.',
    table: {
      type: {
        summary: 'HorizontalCoordinatesGenerator',
      },
      category: 'General',
    },
  },
  horizontalFill: {
    description:
      "Defines background color of stripes.\n\nThe values from this array will be passed in as the `fill` property in a `rect` SVG element.\nFor possible values see: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill#rect\n\nIn case there are more stripes than colors, the colors will start from beginning.\nSo for example: horizontalFill['yellow', 'black'] produces a pattern of yellow|black|yellow|black\n\nIf this is undefined, or an empty array, then there is no background fill.\nNote: Grid lines will be rendered above these background stripes.",
    table: {
      type: {
        summary: 'Array<string>',
      },
      category: 'General',
      defaultValue: {
        summary: '[]',
      },
    },
    defaultValue: [],
  },
  horizontalPoints: {
    description:
      'Array of coordinates in pixels where to draw horizontal grid lines.\nHas priority over syncWithTicks and horizontalValues.',
    table: {
      type: {
        summary: 'Array<number>',
      },
      category: 'General',
      defaultValue: {
        summary: '[]',
      },
    },
    defaultValue: [],
  },
  horizontalValues: {
    description:
      'Array of values, where horizontal lines will be drawn. Numbers or strings, in dependence on axis type.\nHas priority over syncWithTicks but not over horizontalPoints.',
    table: {
      type: {
        summary: 'Array<number> | Array<string>',
      },
      category: 'General',
    },
  },
  strokeDasharray: {
    description: 'The pattern of dashes and gaps used to paint the lines of the grid',
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'Style',
    },
  },
  syncWithTicks: {
    description:
      'If true, only the lines that correspond to the axes ticks values will be drawn.\nIf false, extra lines could be added for each axis (at min and max coordinates), if there will not such ticks.\nhorizontalPoints, verticalPoints, horizontalValues, verticalValues have priority over syncWithTicks.',
    control: {
      type: 'boolean',
    },
    table: {
      type: {
        summary: 'boolean',
      },
      category: 'General',
      defaultValue: {
        summary: 'false',
      },
    },
    defaultValue: false,
  },
  vertical: {
    description: 'If set false, no vertical grid lines will be drawn.',
    table: {
      type: {
        summary: '(union of 5 variants)',
      },
      category: 'General',
      defaultValue: {
        summary: 'true',
      },
    },
    defaultValue: true,
  },
  verticalCoordinatesGenerator: {
    description: 'A function that generates the x-coordinates of all vertical lines.',
    table: {
      type: {
        summary: 'VerticalCoordinatesGenerator',
      },
      category: 'General',
    },
  },
  verticalFill: {
    description:
      "Defines background color of stripes.\n\nThe values from this array will be passed in as the `fill` property in a `rect` SVG element.\nFor possible values see: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill#rect\n\nIn case there are more stripes than colors, the colors will start from beginning.\nSo for example: verticalFill['yellow', 'black'] produces a pattern of yellow|black|yellow|black\n\nIf this is undefined, or an empty array, then there is no background fill.\nNote: Grid lines will be rendered above these background stripes.",
    table: {
      type: {
        summary: 'Array<string>',
      },
      category: 'General',
      defaultValue: {
        summary: '[]',
      },
    },
    defaultValue: [],
  },
  verticalPoints: {
    description:
      'Array of coordinates in pixels where to draw vertical grid lines.\nHas priority over syncWithTicks and verticalValues.',
    table: {
      type: {
        summary: 'Array<number>',
      },
      category: 'General',
      defaultValue: {
        summary: '[]',
      },
    },
    defaultValue: [],
  },
  verticalValues: {
    description:
      'Array of values, where vertical lines will be drawn. Numbers or strings, in dependence on axis type.\nHas priority over syncWithTicks but not over verticalPoints.',
    table: {
      type: {
        summary: 'Array<number> | Array<string>',
      },
      category: 'General',
    },
  },
  width: {
    description: 'The width of grid. If undefined, covers the full width of the chart plot area.',
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  x: {
    description:
      "The x-coordinate of grid.\nIf left undefined, it will be computed from the chart's offset and margins.",
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  xAxisId: {
    description: 'The id of XAxis which is corresponding to the data. Required when there are multiple XAxes.',
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  y: {
    description:
      "The y-coordinate of grid.\nIf left undefined, it will be computed from the chart's offset and margins.",
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  yAxisId: {
    description: 'The id of YAxis which is corresponding to the data. Required when there are multiple YAxes.',
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  zIndex: {
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
      defaultValue: {
        summary: '-100',
      },
    },
    defaultValue: -100,
  },
};
