/**
 * This file is auto-generated by generateStorybookArgsFromSource.ts
 * Do not edit manually.
 */
import { StorybookArgs } from '../../../StorybookArgs';

export const CartesianAxisArgs: StorybookArgs = {
  angle: {
    description: 'Angle in which ticks will be rendered.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
    },
  },
  axisLine: {
    table: {
      type: {
        summary: 'React.SVGProps<SVGLineElement> | false | true',
      },
      category: 'General',
    },
  },
  axisType: {
    table: {
      type: {
        summary: '"xAxis" | "yAxis"',
      },
      category: 'General',
    },
  },
  children: {
    table: {
      type: {
        summary: 'ReactNode',
      },
      category: 'General',
    },
  },
  className: {
    control: {
      type: 'text',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'Style',
    },
  },
  dangerouslySetInnerHTML: {
    table: {
      type: {
        summary: 'Object',
      },
      category: 'General',
    },
  },
  height: {
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  hide: {
    control: {
      type: 'boolean',
    },
    table: {
      type: {
        summary: 'boolean',
      },
      category: 'General',
    },
  },
  interval: {
    table: {
      type: {
        summary: '(union of 6 variants)',
      },
      category: 'General',
    },
  },
  label: {
    table: {
      type: {
        summary: '(union of 7 variants)',
      },
      category: 'General',
    },
  },
  labelRef: {
    table: {
      type: {
        summary: 'React.RefObject<SVGTextElement> | null',
      },
      category: 'General',
    },
  },
  minTickGap: {
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
    },
  },
  mirror: {
    control: {
      type: 'boolean',
    },
    table: {
      type: {
        summary: 'boolean',
      },
      category: 'General',
    },
  },
  onAbort: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAbortCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationEnd: {
    table: {
      type: {
        summary: 'AdaptChildAnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationEndCapture: {
    table: {
      type: {
        summary: 'AdaptChildAnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationIteration: {
    table: {
      type: {
        summary: 'AdaptChildAnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationIterationCapture: {
    table: {
      type: {
        summary: 'AdaptChildAnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationStart: {
    table: {
      type: {
        summary: 'AdaptChildAnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationStartCapture: {
    table: {
      type: {
        summary: 'AdaptChildAnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAuxClick: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAuxClickCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onBeforeInput: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onBeforeInputCapture: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onBlur: {
    table: {
      type: {
        summary: 'AdaptChildFocusEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onBlurCapture: {
    table: {
      type: {
        summary: 'AdaptChildFocusEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCanPlay: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCanPlayCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCanPlayThrough: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCanPlayThroughCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onChange: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onChangeCapture: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onClick: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onClickCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionEnd: {
    table: {
      type: {
        summary: 'AdaptChildCompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionEndCapture: {
    table: {
      type: {
        summary: 'AdaptChildCompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionStart: {
    table: {
      type: {
        summary: 'AdaptChildCompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionStartCapture: {
    table: {
      type: {
        summary: 'AdaptChildCompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionUpdate: {
    table: {
      type: {
        summary: 'AdaptChildCompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionUpdateCapture: {
    table: {
      type: {
        summary: 'AdaptChildCompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onContextMenu: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onContextMenuCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCopy: {
    table: {
      type: {
        summary: 'AdaptChildClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCopyCapture: {
    table: {
      type: {
        summary: 'AdaptChildClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCut: {
    table: {
      type: {
        summary: 'AdaptChildClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCutCapture: {
    table: {
      type: {
        summary: 'AdaptChildClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDoubleClick: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDoubleClickCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDrag: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragEnd: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragEndCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragEnter: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragEnterCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragExit: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragExitCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragLeave: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragLeaveCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragOver: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragOverCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragStart: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragStartCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDrop: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDropCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDurationChange: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDurationChangeCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEmptied: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEmptiedCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEncrypted: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEncryptedCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEnded: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEndedCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onError: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onErrorCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onFocus: {
    table: {
      type: {
        summary: 'AdaptChildFocusEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onFocusCapture: {
    table: {
      type: {
        summary: 'AdaptChildFocusEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onGotPointerCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onGotPointerCaptureCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onInput: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onInputCapture: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onInvalid: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onInvalidCapture: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyDown: {
    table: {
      type: {
        summary: 'AdaptChildKeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyDownCapture: {
    table: {
      type: {
        summary: 'AdaptChildKeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyPress: {
    table: {
      type: {
        summary: 'AdaptChildKeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyPressCapture: {
    table: {
      type: {
        summary: 'AdaptChildKeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyUp: {
    table: {
      type: {
        summary: 'AdaptChildKeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyUpCapture: {
    table: {
      type: {
        summary: 'AdaptChildKeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoad: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadedData: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadedDataCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadedMetadata: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadedMetadataCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadStart: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadStartCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLostPointerCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLostPointerCaptureCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseDown: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseDownCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseEnter: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseLeave: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseMove: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseMoveCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseOut: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseOutCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseOver: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseOverCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseUp: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseUpCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPaste: {
    table: {
      type: {
        summary: 'AdaptChildClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPasteCapture: {
    table: {
      type: {
        summary: 'AdaptChildClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPause: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPauseCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPlay: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPlayCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPlaying: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPlayingCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerCancel: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerCancelCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerDown: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerDownCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerEnter: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerEnterCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerLeave: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerLeaveCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerMove: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerMoveCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerOut: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerOutCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerOver: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerOverCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerUp: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerUpCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onProgress: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onProgressCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onRateChange: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onRateChangeCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onReset: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onResetCapture: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onScroll: {
    table: {
      type: {
        summary: 'AdaptChildUIEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onScrollCapture: {
    table: {
      type: {
        summary: 'AdaptChildUIEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSeeked: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSeekedCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSeeking: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSeekingCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSelect: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSelectCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onStalled: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onStalledCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSubmit: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSubmitCapture: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSuspend: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSuspendCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTimeUpdate: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTimeUpdateCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchCancel: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchCancelCapture: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchEnd: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchEndCapture: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchMove: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchMoveCapture: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchStart: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchStartCapture: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTransitionEnd: {
    table: {
      type: {
        summary: 'AdaptChildTransitionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTransitionEndCapture: {
    table: {
      type: {
        summary: 'AdaptChildTransitionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onVolumeChange: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onVolumeChangeCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onWaiting: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onWaitingCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onWheel: {
    table: {
      type: {
        summary: 'AdaptChildWheelEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onWheelCapture: {
    table: {
      type: {
        summary: 'AdaptChildWheelEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  orientation: {
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  padding: {
    description: 'Padding information passed to custom tick components',
    table: {
      type: {
        summary: '"gap" | "no-gap" | Object',
      },
      category: 'General',
    },
  },
  scale: {
    description: '@deprecated \n\nCartesianAxis reads scale internally and this prop is ignored since 3.0',
    table: {
      type: {
        summary: 'unknown',
      },
      category: 'General',
    },
  },
  tick: {
    table: {
      type: {
        summary: '(union of 5 variants)',
      },
      category: 'General',
    },
  },
  tickFormatter: {
    table: {
      type: {
        summary: 'TickFormatter',
      },
      category: 'General',
    },
  },
  tickLine: {
    table: {
      type: {
        summary: 'React.SVGProps<SVGLineElement> | false | true',
      },
      category: 'General',
    },
  },
  tickMargin: {
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
    },
  },
  ticks: {
    description: 'Careful - this is the same name as XAxis + YAxis `ticks` but completely different object!',
    table: {
      type: {
        summary: 'Array<readonly CartesianTickItem>',
      },
      category: 'General',
    },
  },
  tickSize: {
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
    },
  },
  tickTextProps: {
    description:
      'Additional props to spread to each tick Text element.\nOptional, the CartesianAxis component will provide its own defaults calculated from other props.',
    table: {
      type: {
        summary: 'Props',
      },
      category: 'General',
    },
  },
  unit: {
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  viewBox: {
    table: {
      type: {
        summary: 'CartesianViewBox',
      },
      category: 'General',
    },
  },
  width: {
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  x: {
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  y: {
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  zIndex: {
    description:
      'Z-Index of this component and its children. The higher the value,\nthe more on top it will be rendered.\nComponents with higher zIndex will appear in front of components with lower zIndex.\nIf undefined or 0, the content is rendered in the default layer without portals.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: '0',
  },
};
