/**
 * This file is auto-generated by generateStorybookArgsFromSource.ts
 * Do not edit manually.
 */
import { StorybookArgs } from '../../../StorybookArgs';

export const DefaultLegendContentArgs: StorybookArgs = {
  align: {
    description:
      "Horizontal alignment of the whole Legend container:\n\n- `left`: shows the Legend to the left of the chart, and chart width reduces automatically to make space for it.\n- `right` shows the Legend to the right of the chart, and chart width reduces automatically.\n- `center` shows the Legend in the middle of chart, and chart width remains unchanged.\n\nThe exact behavior changes depending on 'verticalAlign' prop.",
    table: {
      type: {
        summary: '"center" | "left" | "right"',
      },
      category: 'General',
      defaultValue: {
        summary: 'center',
      },
    },
    defaultValue: 'center',
  },
  children: {
    table: {
      type: {
        summary: 'ReactNode',
      },
      category: 'General',
    },
  },
  dangerouslySetInnerHTML: {
    table: {
      type: {
        summary: 'Object',
      },
      category: 'General',
    },
  },
  formatter: {
    description:
      'Function to customize how content is serialized before rendering.\n\nThis should return HTML elements, or strings.',
    table: {
      type: {
        summary: 'Formatter',
      },
      category: 'General',
    },
  },
  iconSize: {
    description: 'The size of icon in each legend item.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
      defaultValue: {
        summary: '14',
      },
    },
    defaultValue: '14',
  },
  iconType: {
    description: 'The type of icon in each legend item.',
    control: {
      type: 'select',
    },
    options: ['none', 'circle', 'cross', 'diamond', 'line', 'plainline', 'rect', 'square', 'star', 'triangle', 'wye'],
    table: {
      type: {
        summary:
          '"circle" | "cross" | "diamond" | "line" | "none" | "plainline" | "rect" | "square" | "star" | "triangle" | "wye"',
      },
      category: 'General',
    },
  },
  inactiveColor: {
    description: 'The color of the icon when the item is inactive.',
    control: {
      type: 'color',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'General',
      defaultValue: {
        summary: '#ccc',
      },
    },
    defaultValue: '#ccc',
  },
  layout: {
    description: 'The layout of legend items inside the legend container.',
    table: {
      type: {
        summary: '"horizontal" | "vertical"',
      },
      category: 'General',
      defaultValue: {
        summary: 'horizontal',
      },
    },
    defaultValue: 'horizontal',
  },
  onAbort: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAbortCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationEnd: {
    table: {
      type: {
        summary: 'AdaptChildAnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationEndCapture: {
    table: {
      type: {
        summary: 'AdaptChildAnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationIteration: {
    table: {
      type: {
        summary: 'AdaptChildAnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationIterationCapture: {
    table: {
      type: {
        summary: 'AdaptChildAnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationStart: {
    table: {
      type: {
        summary: 'AdaptChildAnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationStartCapture: {
    table: {
      type: {
        summary: 'AdaptChildAnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAuxClick: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAuxClickCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onBeforeInput: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onBeforeInputCapture: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onBlur: {
    table: {
      type: {
        summary: 'AdaptChildFocusEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onBlurCapture: {
    table: {
      type: {
        summary: 'AdaptChildFocusEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCanPlay: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCanPlayCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCanPlayThrough: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCanPlayThroughCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onChange: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onChangeCapture: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onClick: {
    description: 'The customized event handler of click on the items in this group',
    table: {
      type: {
        summary: 'Function',
      },
      category: 'Events',
    },
  },
  onClickCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionEnd: {
    table: {
      type: {
        summary: 'AdaptChildCompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionEndCapture: {
    table: {
      type: {
        summary: 'AdaptChildCompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionStart: {
    table: {
      type: {
        summary: 'AdaptChildCompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionStartCapture: {
    table: {
      type: {
        summary: 'AdaptChildCompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionUpdate: {
    table: {
      type: {
        summary: 'AdaptChildCompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionUpdateCapture: {
    table: {
      type: {
        summary: 'AdaptChildCompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onContextMenu: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onContextMenuCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCopy: {
    table: {
      type: {
        summary: 'AdaptChildClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCopyCapture: {
    table: {
      type: {
        summary: 'AdaptChildClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCut: {
    table: {
      type: {
        summary: 'AdaptChildClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCutCapture: {
    table: {
      type: {
        summary: 'AdaptChildClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDoubleClick: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDoubleClickCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDrag: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragEnd: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragEndCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragEnter: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragEnterCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragExit: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragExitCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragLeave: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragLeaveCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragOver: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragOverCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragStart: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragStartCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDrop: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDropCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDurationChange: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDurationChangeCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEmptied: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEmptiedCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEncrypted: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEncryptedCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEnded: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEndedCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onError: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onErrorCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onFocus: {
    table: {
      type: {
        summary: 'AdaptChildFocusEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onFocusCapture: {
    table: {
      type: {
        summary: 'AdaptChildFocusEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onGotPointerCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onGotPointerCaptureCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onInput: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onInputCapture: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onInvalid: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onInvalidCapture: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyDown: {
    table: {
      type: {
        summary: 'AdaptChildKeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyDownCapture: {
    table: {
      type: {
        summary: 'AdaptChildKeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyPress: {
    table: {
      type: {
        summary: 'AdaptChildKeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyPressCapture: {
    table: {
      type: {
        summary: 'AdaptChildKeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyUp: {
    table: {
      type: {
        summary: 'AdaptChildKeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyUpCapture: {
    table: {
      type: {
        summary: 'AdaptChildKeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoad: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadedData: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadedDataCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadedMetadata: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadedMetadataCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadStart: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadStartCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLostPointerCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLostPointerCaptureCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseDown: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseDownCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseEnter: {
    description: 'The customized event handler of mouseenter on the items in this group',
    table: {
      type: {
        summary: 'Function',
      },
      category: 'Events',
    },
  },
  onMouseLeave: {
    description: 'The customized event handler of mouseleave on the items in this group',
    table: {
      type: {
        summary: 'Function',
      },
      category: 'Events',
    },
  },
  onMouseMove: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseMoveCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseOut: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseOutCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseOver: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseOverCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseUp: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseUpCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPaste: {
    table: {
      type: {
        summary: 'AdaptChildClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPasteCapture: {
    table: {
      type: {
        summary: 'AdaptChildClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPause: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPauseCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPlay: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPlayCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPlaying: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPlayingCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerCancel: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerCancelCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerDown: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerDownCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerEnter: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerEnterCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerLeave: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerLeaveCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerMove: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerMoveCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerOut: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerOutCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerOver: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerOverCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerUp: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerUpCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onProgress: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onProgressCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onRateChange: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onRateChangeCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onReset: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onResetCapture: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onScroll: {
    table: {
      type: {
        summary: 'AdaptChildUIEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onScrollCapture: {
    table: {
      type: {
        summary: 'AdaptChildUIEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSeeked: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSeekedCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSeeking: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSeekingCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSelect: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSelectCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onStalled: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onStalledCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSubmit: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSubmitCapture: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSuspend: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSuspendCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTimeUpdate: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTimeUpdateCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchCancel: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchCancelCapture: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchEnd: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchEndCapture: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchMove: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchMoveCapture: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchStart: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchStartCapture: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTransitionEnd: {
    table: {
      type: {
        summary: 'AdaptChildTransitionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTransitionEndCapture: {
    table: {
      type: {
        summary: 'AdaptChildTransitionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onVolumeChange: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onVolumeChangeCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onWaiting: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onWaitingCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onWheel: {
    table: {
      type: {
        summary: 'AdaptChildWheelEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onWheelCapture: {
    table: {
      type: {
        summary: 'AdaptChildWheelEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  payload: {
    description:
      'DefaultLegendContent.payload is omitted from Legend props.\nA custom payload can be passed here if desired, or it can be passed from the Legend "content" callback.',
    table: {
      type: {
        summary: 'Array<LegendPayload>',
      },
      category: 'General',
    },
  },
  verticalAlign: {
    description:
      'Vertical alignment of the whole Legend container:\n\n- `bottom`: shows the Legend below chart, and chart height reduces automatically to make space for it.\n- `top`: shows the Legend above chart, and chart height reduces automatically.\n- `middle`:  shows the Legend in the middle of chart, covering other content, and chart height remains unchanged.\nThe exact behavior changes depending on `align` prop.',
    table: {
      type: {
        summary: '"bottom" | "middle" | "top"',
      },
      category: 'General',
      defaultValue: {
        summary: 'middle',
      },
    },
    defaultValue: 'middle',
  },
};
