/**
 * This file is auto-generated by generateStorybookArgsFromSource.ts
 * Do not edit manually.
 */
import { StorybookArgs } from '../../../StorybookArgs';

export const PolarGridArgs: StorybookArgs = {
  angleAxisId: {
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  cx: {
    description:
      "The x-coordinate of center.\nWhen used inside a chart context, this prop is calculated based on the chart's dimensions,\nand this prop is ignored.\n\nThis is only used when rendered outside a chart context.",
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  cy: {
    description:
      "The y-coordinate of center.\nWhen used inside a chart context, this prop is calculated based on the chart's dimensions,\nand this prop is ignored.\n\nThis is only used when rendered outside a chart context.",
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  gridType: {
    description: 'The type of polar grids.',
    table: {
      type: {
        summary: '"circle" | "polygon"',
      },
      category: 'General',
      defaultValue: {
        summary: 'polygon',
      },
    },
    defaultValue: 'polygon',
  },
  innerRadius: {
    description:
      "The radius of the inner polar grid.\nWhen used inside a chart context, this prop is calculated based on the chart's dimensions,\nand this prop is ignored.\n\nThis is only used when rendered outside a chart context.",
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
    },
  },
  outerRadius: {
    description:
      "The radius of the outer polar grid.\nWhen used inside a chart context, this prop is calculated based on the chart's dimensions,\nand this prop is ignored.\n\nThis is only used when rendered outside a chart context.",
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
    },
  },
  polarAngles: {
    description: "The array of every line grid's angle.",
    table: {
      type: {
        summary: 'Array<readonly number>',
      },
      category: 'General',
    },
  },
  polarRadius: {
    description: "The array of every circle grid's radius.",
    table: {
      type: {
        summary: 'Array<readonly number>',
      },
      category: 'General',
    },
  },
  radialLines: {
    control: {
      type: 'boolean',
    },
    table: {
      type: {
        summary: 'boolean',
      },
      category: 'General',
      defaultValue: {
        summary: 'true',
      },
    },
    defaultValue: true,
  },
  radiusAxisId: {
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  zIndex: {
    description:
      'Z-Index of this component and its children. The higher the value,\nthe more on top it will be rendered.\nComponents with higher zIndex will appear in front of components with lower zIndex.\nIf undefined or 0, the content is rendered in the default layer without portals.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
      defaultValue: {
        summary: '-100',
      },
    },
    defaultValue: -100,
  },
};
