/**
 * This file is auto-generated by generateStorybookArgsFromSource.ts
 * Do not edit manually.
 */
import { StorybookArgs } from '../../../StorybookArgs';

export const PolarAngleAxisArgs: StorybookArgs = {
  allowDataOverflow: {
    description:
      "When domain of the axis is specified and the type of the axis is 'number',\nif allowDataOverflow is set to be false,\nthe domain will be adjusted when the minimum value of data is smaller than domain[0] or\nthe maximum value of data is greater than domain[1] so that the axis displays all data values.\nIf set to true, graphic elements (line, area, bars) will be clipped to conform to the specified domain.",
    control: {
      type: 'boolean',
    },
    table: {
      type: {
        summary: 'boolean',
      },
      category: 'General',
      defaultValue: {
        summary: 'false',
      },
    },
    defaultValue: false,
  },
  allowDecimals: {
    control: {
      type: 'boolean',
    },
    table: {
      type: {
        summary: 'boolean',
      },
      category: 'General',
      defaultValue: {
        summary: 'false',
      },
    },
    defaultValue: false,
  },
  allowDuplicatedCategory: {
    description: 'Allow the axis has duplicated categories or not when the type of axis is "category".',
    control: {
      type: 'boolean',
    },
    table: {
      type: {
        summary: 'boolean',
      },
      category: 'General',
      defaultValue: {
        summary: 'true',
      },
    },
    defaultValue: true,
  },
  angle: {
    description:
      'Tick text rotation angle in degrees.\nPositive values rotate clockwise, negative values rotate counterclockwise.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  angleAxisId: {
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  axisLine: {
    description:
      'Controls axis line element. These are be passed as props to SVG `<line>` element representing the axis line.\nIf `true` then the axis line is drawn using props of the PolarAngleAxis component.\nIf `false` then the axis line is not drawn.\n\nAlso see `axisLineType` prop to change the shape of the axis line.',
    table: {
      type: {
        summary: 'React.SVGProps<SVGLineElement> | false | true',
      },
      category: 'General',
      defaultValue: {
        summary: 'true',
      },
    },
    defaultValue: true,
  },
  axisLineType: {
    description: 'The type of axis line.',
    table: {
      type: {
        summary: '"circle" | "polygon"',
      },
      category: 'General',
      defaultValue: {
        summary: 'polygon',
      },
    },
    defaultValue: 'polygon',
  },
  children: {
    table: {
      type: {
        summary: 'ReactNode',
      },
      category: 'General',
    },
  },
  className: {
    description: "The HTML element's class name",
    control: {
      type: 'text',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'Style',
    },
  },
  cx: {
    description:
      "The x-coordinate of center.\nWhen used inside a chart context, this prop is calculated based on the chart's dimensions,\nand this prop is ignored.\n\nThis is only used when rendered outside a chart context.",
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  cy: {
    description:
      "The y-coordinate of center.\nWhen used inside a chart context, this prop is calculated based on the chart's dimensions,\nand this prop is ignored.\n\nThis is only used when rendered outside a chart context.",
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  dataKey: {
    description:
      'Decides how to extract the value of this Axis from the data:\n- `string`: the name of the field in the data object;\n- `number`: the index of the field in the data;\n- `function`: a function that receives the data object and returns the value of this Axis.\n\nIf undefined, it will reuse the dataKey of graphical items.',
    table: {
      type: {
        summary: 'Function | number | string',
      },
      category: 'General',
    },
  },
  domain: {
    description:
      "Specify the domain of axis when the axis is a number axis.\n\nIf undefined, then the domain is calculated based on the data and dataKeys.\n\nThe length of domain should be 2, and we will validate the values in domain.\n\nEach element in the array can be a number, 'auto', 'dataMin', 'dataMax', a string like 'dataMin - 20', 'dataMax + 100',\nor a function that accepts a single argument and returns a number.\n\nIf any element of domain is set to be 'auto', comprehensible scale ticks will be calculated, and the final domain of axis is generated by the ticks.\nIf a function, receives '[dataMin, dataMax]', and must return a computed domain as '[min, max]'.",
    table: {
      type: {
        summary: 'Array<number> | Array<string> | Function | [AxisDomainItem, AxisDomainItem]',
      },
      category: 'General',
    },
  },
  hide: {
    description: 'If set true, the axis do not display in the chart.',
    control: {
      type: 'boolean',
    },
    table: {
      type: {
        summary: 'boolean',
      },
      category: 'General',
      defaultValue: {
        summary: 'false',
      },
    },
    defaultValue: false,
  },
  includeHidden: {
    description:
      'Ensures that all datapoints within a chart contribute to its domain calculation, even when they are hidden',
    control: {
      type: 'boolean',
    },
    table: {
      type: {
        summary: 'boolean',
      },
      category: 'General',
      defaultValue: {
        summary: 'false',
      },
    },
    defaultValue: false,
  },
  label: {
    description:
      'Defines a single label for the whole axis.\nThis prop renders one label in the center of the axis line.\nUseful for labeling the axis as a whole, like "Time (in seconds)" or "Distance (in meters)".\n\nThis is not controlling tick labels.\nIf you want to customize tick labels, please see `tickFormatter` or `tick` props.\n\n- `false`: no label is rendered\n- `string` | `number`: the content of the label\n- `object`: the props of LabelList component\n- `ReactElement`: a custom label element\n- `function`: a render function of custom label',
    table: {
      type: {
        summary: '(union of 7 variants)',
      },
      category: 'General',
      defaultValue: {
        summary: 'false',
      },
    },
    defaultValue: false,
  },
  name: {
    description:
      'The name of data.\nThis option will be used in tooltip.\nIf no value was set to this option, the value of dataKey will be used alternatively.',
    control: {
      type: 'text',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'General',
    },
  },
  onAbort: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAbortCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationEnd: {
    table: {
      type: {
        summary: 'AdaptChildAnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationEndCapture: {
    table: {
      type: {
        summary: 'AdaptChildAnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationIteration: {
    table: {
      type: {
        summary: 'AdaptChildAnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationIterationCapture: {
    table: {
      type: {
        summary: 'AdaptChildAnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationStart: {
    table: {
      type: {
        summary: 'AdaptChildAnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAnimationStartCapture: {
    table: {
      type: {
        summary: 'AdaptChildAnimationEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAuxClick: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onAuxClickCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onBeforeInput: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onBeforeInputCapture: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onBlur: {
    table: {
      type: {
        summary: 'AdaptChildFocusEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onBlurCapture: {
    table: {
      type: {
        summary: 'AdaptChildFocusEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCanPlay: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCanPlayCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCanPlayThrough: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCanPlayThroughCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onChange: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onChangeCapture: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onClick: {
    description: 'The customized event handler of click on the ticks of this axis',
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onClickCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionEnd: {
    table: {
      type: {
        summary: 'AdaptChildCompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionEndCapture: {
    table: {
      type: {
        summary: 'AdaptChildCompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionStart: {
    table: {
      type: {
        summary: 'AdaptChildCompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionStartCapture: {
    table: {
      type: {
        summary: 'AdaptChildCompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionUpdate: {
    table: {
      type: {
        summary: 'AdaptChildCompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCompositionUpdateCapture: {
    table: {
      type: {
        summary: 'AdaptChildCompositionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onContextMenu: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onContextMenuCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCopy: {
    table: {
      type: {
        summary: 'AdaptChildClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCopyCapture: {
    table: {
      type: {
        summary: 'AdaptChildClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCut: {
    table: {
      type: {
        summary: 'AdaptChildClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onCutCapture: {
    table: {
      type: {
        summary: 'AdaptChildClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDoubleClick: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDoubleClickCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDrag: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragEnd: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragEndCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragEnter: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragEnterCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragExit: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragExitCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragLeave: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragLeaveCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragOver: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragOverCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragStart: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDragStartCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDrop: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDropCapture: {
    table: {
      type: {
        summary: 'AdaptChildDragEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDurationChange: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onDurationChangeCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEmptied: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEmptiedCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEncrypted: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEncryptedCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEnded: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onEndedCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onError: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onErrorCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onFocus: {
    table: {
      type: {
        summary: 'AdaptChildFocusEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onFocusCapture: {
    table: {
      type: {
        summary: 'AdaptChildFocusEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onGotPointerCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onGotPointerCaptureCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onInput: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onInputCapture: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onInvalid: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onInvalidCapture: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyDown: {
    table: {
      type: {
        summary: 'AdaptChildKeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyDownCapture: {
    table: {
      type: {
        summary: 'AdaptChildKeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyPress: {
    table: {
      type: {
        summary: 'AdaptChildKeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyPressCapture: {
    table: {
      type: {
        summary: 'AdaptChildKeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyUp: {
    table: {
      type: {
        summary: 'AdaptChildKeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onKeyUpCapture: {
    table: {
      type: {
        summary: 'AdaptChildKeyboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoad: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadedData: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadedDataCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadedMetadata: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadedMetadataCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadStart: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLoadStartCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLostPointerCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onLostPointerCaptureCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseDown: {
    description: 'The customized event handler of mousedown on the ticks of this axis',
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseDownCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseEnter: {
    description: 'The customized event handler of mouseenter on the ticks of this axis',
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseLeave: {
    description: 'The customized event handler of mouseleave on the ticks of this axis',
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseMove: {
    description: 'The customized event handler of mousemove on the ticks of this axis',
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseMoveCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseOut: {
    description: 'The customized event handler of mouseout on the ticks of this axis',
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseOutCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseOver: {
    description: 'The customized event handler of mouseover on the ticks of this axis',
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseOverCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseUp: {
    description: 'The customized event handler of mouseup on the ticks of this axis',
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onMouseUpCapture: {
    table: {
      type: {
        summary: 'AdaptChildMouseEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPaste: {
    table: {
      type: {
        summary: 'AdaptChildClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPasteCapture: {
    table: {
      type: {
        summary: 'AdaptChildClipboardEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPause: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPauseCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPlay: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPlayCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPlaying: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPlayingCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerCancel: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerCancelCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerDown: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerDownCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerEnter: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerEnterCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerLeave: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerLeaveCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerMove: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerMoveCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerOut: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerOutCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerOver: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerOverCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerUp: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onPointerUpCapture: {
    table: {
      type: {
        summary: 'AdaptChildPointerEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onProgress: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onProgressCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onRateChange: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onRateChangeCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onReset: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onResetCapture: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onScroll: {
    table: {
      type: {
        summary: 'AdaptChildUIEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onScrollCapture: {
    table: {
      type: {
        summary: 'AdaptChildUIEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSeeked: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSeekedCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSeeking: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSeekingCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSelect: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSelectCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onStalled: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onStalledCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSubmit: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSubmitCapture: {
    table: {
      type: {
        summary: 'AdaptChildFormEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSuspend: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onSuspendCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTimeUpdate: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTimeUpdateCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchCancel: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchCancelCapture: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchEnd: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchEndCapture: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchMove: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchMoveCapture: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchStart: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTouchStartCapture: {
    table: {
      type: {
        summary: 'AdaptChildTouchEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTransitionEnd: {
    table: {
      type: {
        summary: 'AdaptChildTransitionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onTransitionEndCapture: {
    table: {
      type: {
        summary: 'AdaptChildTransitionEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onVolumeChange: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onVolumeChangeCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onWaiting: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onWaitingCapture: {
    table: {
      type: {
        summary: 'AdaptChildReactEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onWheel: {
    table: {
      type: {
        summary: 'AdaptChildWheelEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  onWheelCapture: {
    table: {
      type: {
        summary: 'AdaptChildWheelEventHandler<P, T>',
      },
      category: 'Events',
    },
  },
  orientation: {
    description: 'The orientation of axis text.',
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
      defaultValue: {
        summary: 'outer',
      },
    },
    defaultValue: 'outer',
  },
  radius: {
    description:
      'The outer radius of circle grid.\nIf set a percentage, the final value is obtained by multiplying the percentage of maxRadius which is calculated by the width, height, cx, cy.',
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  range: {
    table: {
      type: {
        summary: 'AxisRange',
      },
      category: 'General',
    },
    description:
      '@deprecated Recharts computes the range automatically based on chart width or height\n\nRecharts ignores this prop since 3.0',
  },
  reversed: {
    description: 'If set to true, the ticks of this axis are reversed.',
    control: {
      type: 'boolean',
    },
    table: {
      type: {
        summary: 'boolean',
      },
      category: 'General',
      defaultValue: {
        summary: 'false',
      },
    },
    defaultValue: false,
  },
  scale: {
    description:
      "Scale function determines how data values are mapped to visual values.\nIn other words, decided the mapping between data domain and coordinate range.\n\nIf undefined, or 'auto', the scale function is created internally according to the type of axis and data.\n\nYou can define a custom scale, either as a string shortcut to a d3 scale, or as a complete scale definition object.",
    table: {
      type: {
        summary: '(union of 20 variants)',
      },
      category: 'General',
      defaultValue: {
        summary: 'auto',
      },
    },
    defaultValue: 'auto',
  },
  tick: {
    description:
      'Defines how the individual label text is rendered.\nThis controls the settings for individual ticks; on a typical axis, there are multiple ticks, depending on your data.\n\nIf you want to customize the overall axis label, use the `label` prop instead.\n\nOptions:\n- `false`: Do not render any tick labels.\n- `true`: Render tick labels with default settings.\n- `object`: An object of props to be merged into the internally calculated tick props.\n- `ReactElement`: A custom React element to be used as the tick label.\n- `function`: A function that returns a React element for custom rendering of tick labels.',
    table: {
      type: {
        summary: '(union of 5 variants)',
      },
      category: 'General',
      defaultValue: {
        summary: 'true',
      },
    },
    defaultValue: true,
  },
  tickCount: {
    description: "The count of axis ticks. Not used if 'type' is 'category'.",
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
    },
  },
  tickFormatter: {
    description: 'The formatter function of ticks.',
    table: {
      type: {
        summary: 'Function',
      },
      category: 'General',
    },
  },
  tickLine: {
    description:
      'If false set, tick lines will not be drawn.\nIf true set, tick lines will be drawn which have the props calculated internally.\nIf object set, tick lines will be drawn which have the props merged\nby the internal calculated props and the option.',
    table: {
      type: {
        summary: 'React.SVGProps<SVGLineElement> | false | true',
      },
      category: 'General',
      defaultValue: {
        summary: 'true',
      },
    },
    defaultValue: true,
  },
  ticks: {
    description: "The array of every tick's value and angle.",
    table: {
      type: {
        summary: 'Array<TickItem>',
      },
      category: 'General',
    },
  },
  tickSize: {
    description: 'The length of tick line.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
      defaultValue: {
        summary: '8',
      },
    },
    defaultValue: 8,
  },
  type: {
    description:
      'The type of axis.\n\n`category`: Treats data as distinct values.\nEach value is in the same distance from its neighbors, regardless of their actual numeric difference.\n\n`number`: Treats data as continuous range.\nValues that are numerically closer are placed closer together on the axis.\n\n`auto`: the type is inferred based on the chart layout.',
    control: {
      type: 'select',
    },
    options: ['number', 'auto', 'category'],
    table: {
      type: {
        summary: '"auto" | "category" | "number"',
      },
      category: 'General',
      defaultValue: {
        summary: 'auto',
      },
    },
    defaultValue: 'auto',
  },
  unit: {
    description: 'The unit of data. This option will be used in tooltip.',
    control: {
      type: 'text',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'General',
    },
  },
  zIndex: {
    description:
      'Z-Index of this component and its children. The higher the value,\nthe more on top it will be rendered.\nComponents with higher zIndex will appear in front of components with lower zIndex.\nIf undefined or 0, the content is rendered in the default layer without portals.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
      defaultValue: {
        summary: '500',
      },
    },
    defaultValue: 500,
  },
};
