/**
 * This file is auto-generated by generateStorybookArgsFromSource.ts
 * Do not edit manually.
 */
import { StorybookArgs } from '../../../StorybookArgs';

export const PolygonArgs: StorybookArgs = {
  baseLinePoints: {
    table: {
      type: {
        summary: 'Array<readonly Coordinate>',
      },
      category: 'General',
    },
  },
  className: {
    control: {
      type: 'text',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'Style',
    },
  },
  connectNulls: {
    control: {
      type: 'boolean',
    },
    table: {
      type: {
        summary: 'boolean',
      },
      category: 'General',
    },
  },
  onClick: {
    description: 'The customized event handler of click on the polygon',
    table: {
      type: {
        summary: 'React.MouseEventHandler<T>',
      },
      category: 'Events',
    },
  },
  onMouseDown: {
    description: 'The customized event handler of mousedown on the polygon',
    table: {
      type: {
        summary: 'React.MouseEventHandler<T>',
      },
      category: 'Events',
    },
  },
  onMouseEnter: {
    description: 'The customized event handler of mouseenter on the polygon',
    table: {
      type: {
        summary: 'React.MouseEventHandler<T>',
      },
      category: 'Events',
    },
  },
  onMouseLeave: {
    description: 'The customized event handler of mouseleave on the polygon',
    table: {
      type: {
        summary: 'React.MouseEventHandler<T>',
      },
      category: 'Events',
    },
  },
  onMouseMove: {
    description: 'The customized event handler of mousemove on the polygon',
    table: {
      type: {
        summary: 'React.MouseEventHandler<T>',
      },
      category: 'Events',
    },
  },
  onMouseOut: {
    description: 'The customized event handler of mouseout on the polygon',
    table: {
      type: {
        summary: 'React.MouseEventHandler<T>',
      },
      category: 'Events',
    },
  },
  onMouseOver: {
    description: 'The customized event handler of mouseover on the polygon',
    table: {
      type: {
        summary: 'React.MouseEventHandler<T>',
      },
      category: 'Events',
    },
  },
  onMouseUp: {
    description: 'The customized event handler of mouseup on the polygon',
    table: {
      type: {
        summary: 'React.MouseEventHandler<T>',
      },
      category: 'Events',
    },
  },
  points: {
    description:
      'The coordinates of all the vertexes of the polygon, like an array of objects with x and y coordinates.',
    table: {
      type: {
        summary: 'Array<readonly Coordinate>',
      },
      category: 'General',
    },
  },
};
