/**
 * This file is auto-generated by generateStorybookArgsFromSource.ts
 * Do not edit manually.
 */
import { StorybookArgs } from '../../../StorybookArgs';

export const RadarArgs: StorybookArgs = {
  activeDot: {
    table: {
      type: {
        summary: 'Function | Partial<ActiveDotProps> | ReactNode | false | true',
      },
      category: 'General',
      defaultValue: {
        summary: 'true',
      },
    },
    defaultValue: true,
  },
  angleAxisId: {
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  animationBegin: {
    description: 'Specifies when the animation should begin, the unit of this option is ms.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'Animation',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  animationDuration: {
    description: 'Specifies the duration of animation, the unit of this option is ms.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'Animation',
      defaultValue: {
        summary: '1500',
      },
    },
    defaultValue: 1500,
  },
  animationEasing: {
    description: 'The type of easing function.',
    control: {
      type: 'select',
    },
    options: ['linear', 'ease', 'ease-in', 'ease-out', 'ease-in-out'],
    table: {
      type: {
        summary: '"ease" | "ease-in" | "ease-in-out" | "ease-out" | "linear"',
      },
      category: 'Animation',
      defaultValue: {
        summary: 'ease',
      },
    },
    defaultValue: 'ease',
  },
  baseLinePoints: {
    table: {
      type: {
        summary: 'Array<RadarPoint>',
      },
      category: 'General',
    },
  },
  className: {
    control: {
      type: 'text',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'Style',
    },
  },
  connectNulls: {
    control: {
      type: 'boolean',
    },
    table: {
      type: {
        summary: 'boolean',
      },
      category: 'General',
    },
  },
  dataKey: {
    description:
      'Decides how to extract the value of this Radar from the data:\n- `string`: the name of the field in the data object;\n- `number`: the index of the field in the data;\n- `function`: a function that receives the data object and returns the value of this Radar.',
    table: {
      type: {
        summary: 'Function | number | string',
      },
      category: 'General',
    },
  },
  dot: {
    description:
      'Renders a circle element at each data point. Options:\n\n- `false`: no dots are drawn;\n- `true`: renders the dots with default settings;\n- `object`: the props of the dot. This will be merged with the internal calculated props of each dot;\n- `ReactElement`: the custom dot element;\n- `function`: a render function of the custom dot.',
    table: {
      type: {
        summary: 'Function | Partial<Props> | ReactNode | false | true',
      },
      category: 'General',
      defaultValue: {
        summary: 'false',
      },
    },
    defaultValue: false,
  },
  hide: {
    control: {
      type: 'boolean',
    },
    table: {
      type: {
        summary: 'boolean',
      },
      category: 'General',
      defaultValue: {
        summary: 'false',
      },
    },
    defaultValue: false,
  },
  isAnimationActive: {
    description:
      'If set false, animation of polygon will be disabled.\nIf set "auto", the animation will be disabled in SSR and enabled in browser.',
    table: {
      type: {
        summary: '"auto" | false | true',
      },
      category: 'Animation',
      defaultValue: {
        summary: 'auto',
      },
    },
    defaultValue: 'auto',
  },
  isRange: {
    control: {
      type: 'boolean',
    },
    table: {
      type: {
        summary: 'boolean',
      },
      category: 'General',
    },
  },
  label: {
    description:
      'Renders one label for each point. Options:\n- `true`: renders default labels;\n- `false`: no labels are rendered;\n- `object`: the props of LabelList component;\n- `ReactElement`: a custom label element;\n- `function`: a render function of custom label.',
    table: {
      type: {
        summary: 'Function | Props | ReactNode | false | true',
      },
      category: 'General',
      defaultValue: {
        summary: 'false',
      },
    },
    defaultValue: false,
  },
  legendType: {
    description: "The type of icon in legend.  If set to 'none', no legend item will be rendered.",
    control: {
      type: 'select',
    },
    options: ['none', 'circle', 'cross', 'diamond', 'line', 'plainline', 'rect', 'square', 'star', 'triangle', 'wye'],
    table: {
      type: {
        summary:
          '"circle" | "cross" | "diamond" | "line" | "none" | "plainline" | "rect" | "square" | "star" | "triangle" | "wye"',
      },
      category: 'General',
      defaultValue: {
        summary: 'rect',
      },
    },
    defaultValue: 'rect',
  },
  onAnimationEnd: {
    description: 'The customized event handler of animation end',
    table: {
      type: {
        summary: 'React.AnimationEventHandler<T>',
      },
      category: 'Events',
    },
  },
  onAnimationStart: {
    description: 'The customized event handler of animation start',
    table: {
      type: {
        summary: 'React.AnimationEventHandler<T>',
      },
      category: 'Events',
    },
  },
  onMouseEnter: {
    table: {
      type: {
        summary: 'Function',
      },
      category: 'Events',
    },
  },
  onMouseLeave: {
    table: {
      type: {
        summary: 'Function',
      },
      category: 'Events',
    },
  },
  points: {
    description:
      'The coordinates of all the vertexes of the radar shape, like an array of objects with x and y coordinates.',
    table: {
      type: {
        summary: 'Array<RadarPoint>',
      },
      category: 'General',
    },
  },
  radiusAxisId: {
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  shape: {
    description:
      'If set a ReactElement, the shape of radar can be customized.\nIf set a function, the function will be called to render customized shape.',
    table: {
      type: {
        summary: 'Function | ReactNode',
      },
      category: 'General',
    },
  },
  tooltipType: {
    table: {
      type: {
        summary: '"none"',
      },
      category: 'General',
    },
  },
  zIndex: {
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
      defaultValue: {
        summary: '100',
      },
    },
    defaultValue: 100,
  },
};
