/**
 * This file is auto-generated by generateStorybookArgsFromSource.ts
 * Do not edit manually.
 */
import { StorybookArgs } from '../../../StorybookArgs';

export const ReferenceAreaArgs: StorybookArgs = {
  children: {
    table: {
      type: {
        summary: 'ReactNode',
      },
      category: 'General',
    },
  },
  className: {
    control: {
      type: 'text',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'Style',
    },
  },
  ifOverflow: {
    description:
      'Defines how to draw this component if it falls partly outside the canvas:\n\n- `discard`: the whole component will not be drawn at all\n- `hidden`: the component will be clipped to the chart plot area\n- `visible`: the component will be drawn completely\n- `extendDomain`: the domain of the overflown axis will be extended such that the whole component fits into the plot area',
    table: {
      type: {
        summary: '"discard" | "extendDomain" | "hidden" | "visible"',
      },
      category: 'General',
      defaultValue: {
        summary: 'discard',
      },
    },
    defaultValue: 'discard',
  },
  label: {
    description:
      'Renders a single label.\n\n- `false`: no labels are rendered\n- `string` | `number`: the content of the label\n- `object`: the props of LabelList component\n- `ReactElement`: a custom label element\n- `function`: a render function of custom label',
    table: {
      type: {
        summary: '(union of 7 variants)',
      },
      category: 'General',
      defaultValue: {
        summary: 'false',
      },
    },
    defaultValue: false,
  },
  onClick: {
    description: 'The customized event handler of click on the rectangle',
    table: {
      type: {
        summary: 'React.MouseEventHandler<T>',
      },
      category: 'Events',
    },
  },
  onMouseDown: {
    description: 'The customized event handler of mousedown on the rectangle',
    table: {
      type: {
        summary: 'React.MouseEventHandler<T>',
      },
      category: 'Events',
    },
  },
  onMouseEnter: {
    description: 'The customized event handler of mouseenter on the rectangle',
    table: {
      type: {
        summary: 'React.MouseEventHandler<T>',
      },
      category: 'Events',
    },
  },
  onMouseLeave: {
    description: 'The customized event handler of mouseleave on the rectangle',
    table: {
      type: {
        summary: 'React.MouseEventHandler<T>',
      },
      category: 'Events',
    },
  },
  onMouseMove: {
    description: 'The customized event handler of mousemove on the rectangle',
    table: {
      type: {
        summary: 'React.MouseEventHandler<T>',
      },
      category: 'Events',
    },
  },
  onMouseOut: {
    description: 'The customized event handler of mouseout on the rectangle',
    table: {
      type: {
        summary: 'React.MouseEventHandler<T>',
      },
      category: 'Events',
    },
  },
  onMouseOver: {
    description: 'The customized event handler of mouseover on the rectangle',
    table: {
      type: {
        summary: 'React.MouseEventHandler<T>',
      },
      category: 'Events',
    },
  },
  onMouseUp: {
    description: 'The customized event handler of mouseup on the rectangle',
    table: {
      type: {
        summary: 'React.MouseEventHandler<T>',
      },
      category: 'Events',
    },
  },
  radius: {
    description:
      'The radius of corners.\n\nIf you provide a single number, it applies to all four corners.\nIf you provide an array of four numbers, they apply to top-left, top-right, bottom-right, bottom-left corners respectively.',
    table: {
      type: {
        summary: '[number, number, number, number] | number',
      },
      category: 'General',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  shape: {
    description:
      'If set a ReactElement, the shape of the reference area can be customized.\nIf set a function, the function will be called to render customized shape.',
    table: {
      type: {
        summary: 'Function | ReactNode',
      },
      category: 'General',
    },
  },
  x1: {
    description:
      "Starting X-coordinate of the area.\nThis value is using your chart's domain, so you will provide a data value instead of a pixel value.\nReferenceArea will internally calculate the correct pixel position.\n\nIf undefined then the area will extend to the left edge of the chart plot area.",
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  x2: {
    description:
      "Ending X-coordinate of the area.\nThis value is using your chart's domain, so you will provide a data value instead of a pixel value.\nReferenceArea will internally calculate the correct pixel position.\n\nIf undefined then the area will extend to the right edge of the chart plot area.",
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  xAxisId: {
    description: 'The id of XAxis which is corresponding to the data. Required when there are multiple XAxes.',
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  y1: {
    description:
      "Starting Y-coordinate of the area.\nThis value is using your chart's domain, so you will provide a data value instead of a pixel value.\nReferenceArea will internally calculate the correct pixel position.\n\nIf undefined then the area will extend to the top edge of the chart plot area.",
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  y2: {
    description:
      "Ending Y-coordinate of the area.\nThis value is using your chart's domain, so you will provide a data value instead of a pixel value.\nReferenceArea will internally calculate the correct pixel position.\n\nIf undefined then the area will extend to the bottom edge of the chart plot area.",
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  yAxisId: {
    description: 'The id of YAxis which is corresponding to the data. Required when there are multiple YAxes.',
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  zIndex: {
    description:
      'Z-Index of this component and its children. The higher the value,\nthe more on top it will be rendered.\nComponents with higher zIndex will appear in front of components with lower zIndex.\nIf undefined or 0, the content is rendered in the default layer without portals.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
      defaultValue: {
        summary: '100',
      },
    },
    defaultValue: 100,
  },
};
