/**
 * This file is auto-generated by generateStorybookArgsFromSource.ts
 * Do not edit manually.
 */
import { StorybookArgs } from '../../../StorybookArgs';

export const SunburstChartArgs: StorybookArgs = {
  children: {
    table: {
      type: {
        summary: 'ReactNode',
      },
      category: 'General',
    },
  },
  className: {
    control: {
      type: 'text',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'Style',
    },
  },
  cx: {
    description: 'The x-coordinate of center in pixels.\nIf undefined, it will be set to half of the chart width.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
    },
  },
  cy: {
    description: 'The y-coordinate of center in pixels.\nIf undefined, it will be set to half of the chart height.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
    },
  },
  data: {
    description:
      'The source data. Each element should be an object.\nThe properties of each object represent the values of different data dimensions.\n\nUse the `dataKey` prop to specify which properties to use.',
    table: {
      type: {
        summary: 'SunburstData',
      },
      category: 'General',
    },
  },
  dataKey: {
    description:
      'Decides how to extract value from the data:\n- `string`: the name of the field in the data object;\n- `number`: the index of the field in the data;\n- `function`: a function that receives the data object and returns the value.',
    control: {
      type: 'text',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'General',
      defaultValue: {
        summary: 'value',
      },
    },
    defaultValue: 'value',
  },
  endAngle: {
    description: 'Angle, in degrees, at which the chart should end.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
    },
  },
  fill: {
    control: {
      type: 'color',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'Style',
    },
  },
  height: {
    description: 'The height of chart container.\nCan be a number or a percent string like "100%".',
    table: {
      type: {
        summary: '`${number}%` | number',
      },
      category: 'General',
    },
  },
  id: {
    control: {
      type: 'text',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'General',
    },
  },
  innerRadius: {
    description: 'The radius of the inner circle at the center of the chart.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
      defaultValue: {
        summary: '50',
      },
    },
    defaultValue: '50',
  },
  nameKey: {
    description:
      'Decides how to extract name from the data:\n- `string`: the name of the field in the data object;\n- `number`: the index of the field in the data;\n- `function`: a function that receives the data object and returns the name.',
    table: {
      type: {
        summary: 'Function | number | string',
      },
      category: 'General',
      defaultValue: {
        summary: 'name',
      },
    },
    defaultValue: 'name',
  },
  onClick: {
    table: {
      type: {
        summary: 'Function',
      },
      category: 'Events',
    },
  },
  onMouseEnter: {
    table: {
      type: {
        summary: 'Function',
      },
      category: 'Events',
    },
  },
  onMouseLeave: {
    table: {
      type: {
        summary: 'Function',
      },
      category: 'Events',
    },
  },
  outerRadius: {
    description:
      'Outermost edge of the chart.\nDefaults to the max possible radius for a circle inscribed in the chart container',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
    },
  },
  padding: {
    description: 'The padding between sectors.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
      defaultValue: {
        summary: '2',
      },
    },
    defaultValue: '2',
  },
  responsive: {
    description:
      'If true, then it will listen to container size changes and adapt the SVG chart accordingly.\nIf false, then it renders the chart at the specified width and height and will stay that way\neven if the container size changes.\n\nThis is similar to ResponsiveContainer but without the need for an extra wrapper component.\nThe `responsive` prop also uses standard CSS sizing rules, instead of custom resolution logic (like ResponsiveContainer does).',
    control: {
      type: 'boolean',
    },
    table: {
      type: {
        summary: 'boolean',
      },
      category: 'General',
      defaultValue: {
        summary: 'false',
      },
    },
    defaultValue: 'false',
  },
  ringPadding: {
    description: 'Padding between each hierarchical level.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
    },
  },
  startAngle: {
    description: 'Angle in degrees from which the chart should start.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
    },
  },
  stroke: {
    control: {
      type: 'color',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'Style',
    },
  },
  style: {
    table: {
      type: {
        summary: 'React.CSSProperties',
      },
      category: 'Style',
    },
  },
  textOptions: {
    description: 'An object with svg text options to control the appearance of the chart labels.',
    table: {
      type: {
        summary: 'Props',
      },
      category: 'General',
    },
  },
  width: {
    description: 'The width of chart container.\nCan be a number or a percent string like "100%".',
    table: {
      type: {
        summary: '`${number}%` | number',
      },
      category: 'General',
    },
  },
};
