/**
 * This file is auto-generated by generateStorybookArgsFromSource.ts
 * Do not edit manually.
 */
import { StorybookArgs } from '../../../StorybookArgs';

export const SurfaceArgs: StorybookArgs = {
  children: {
    table: {
      type: {
        summary: 'ReactNode',
      },
      category: 'General',
    },
  },
  className: {
    control: {
      type: 'text',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'Style',
    },
  },
  desc: {
    control: {
      type: 'text',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'General',
    },
  },
  height: {
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
  style: {
    table: {
      type: {
        summary: 'React.CSSProperties',
      },
      category: 'Style',
    },
  },
  title: {
    control: {
      type: 'text',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'General',
    },
  },
  viewBox: {
    table: {
      type: {
        summary: 'CartesianViewBox',
      },
      category: 'General',
    },
  },
  width: {
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
    },
  },
};
