/**
 * This file is auto-generated by generateStorybookArgsFromSource.ts
 * Do not edit manually.
 */
import { StorybookArgs } from '../../../StorybookArgs';

export const TrapezoidArgs: StorybookArgs = {
  animationBegin: {
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'Animation',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  animationDuration: {
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'Animation',
      defaultValue: {
        summary: '1500',
      },
    },
    defaultValue: 1500,
  },
  animationEasing: {
    control: {
      type: 'select',
    },
    options: ['linear', 'ease', 'ease-in', 'ease-out', 'ease-in-out'],
    table: {
      type: {
        summary: '"ease" | "ease-in" | "ease-in-out" | "ease-out" | "linear"',
      },
      category: 'Animation',
      defaultValue: {
        summary: 'ease',
      },
    },
    defaultValue: 'ease',
  },
  className: {
    control: {
      type: 'text',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'Style',
    },
  },
  height: {
    description: 'Height of the trapezoid in pixels.',
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  isUpdateAnimationActive: {
    description:
      'If set to true, trapezoid will update and render with a gradual fade-in animation from left to right.',
    control: {
      type: 'boolean',
    },
    table: {
      type: {
        summary: 'boolean',
      },
      category: 'Animation',
      defaultValue: {
        summary: 'false',
      },
    },
    defaultValue: false,
  },
  lowerWidth: {
    description: 'Width of the lower horizontal side of the trapezoid in pixels.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  onClick: {
    description: 'The customized event handler of click on the trapezoid',
    table: {
      type: {
        summary: 'React.MouseEventHandler<T>',
      },
      category: 'Events',
    },
  },
  onMouseDown: {
    description: 'The customized event handler of mousedown on the trapezoid',
    table: {
      type: {
        summary: 'React.MouseEventHandler<T>',
      },
      category: 'Events',
    },
  },
  onMouseEnter: {
    description: 'The customized event handler of mouseenter on the trapezoid',
    table: {
      type: {
        summary: 'React.MouseEventHandler<T>',
      },
      category: 'Events',
    },
  },
  onMouseLeave: {
    description: 'The customized event handler of mouseleave on the trapezoid',
    table: {
      type: {
        summary: 'React.MouseEventHandler<T>',
      },
      category: 'Events',
    },
  },
  onMouseMove: {
    description: 'The customized event handler of mousemove on the trapezoid',
    table: {
      type: {
        summary: 'React.MouseEventHandler<T>',
      },
      category: 'Events',
    },
  },
  onMouseOut: {
    description: 'The customized event handler of mouseout on the trapezoid',
    table: {
      type: {
        summary: 'React.MouseEventHandler<T>',
      },
      category: 'Events',
    },
  },
  onMouseOver: {
    description: 'The customized event handler of mouseover on the trapezoid',
    table: {
      type: {
        summary: 'React.MouseEventHandler<T>',
      },
      category: 'Events',
    },
  },
  onMouseUp: {
    description: 'The customized event handler of mouseup on the trapezoid',
    table: {
      type: {
        summary: 'React.MouseEventHandler<T>',
      },
      category: 'Events',
    },
  },
  upperWidth: {
    description: 'Width of the upper horizontal side of the trapezoid in pixels.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  x: {
    description: 'The x-coordinate of top left point of the trapezoid.',
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  y: {
    description: 'The y-coordinate of top left point of the trapezoid.',
    table: {
      type: {
        summary: 'number | string',
      },
      category: 'General',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
};
