/**
 * This file is auto-generated by generateStorybookArgsFromSource.ts
 * Do not edit manually.
 */
import { StorybookArgs } from '../../../StorybookArgs';

export const TreemapArgs: StorybookArgs = {
  animationBegin: {
    description: 'Specifies when the animation should begin, the unit of this option is ms.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'Animation',
      defaultValue: {
        summary: '0',
      },
    },
    defaultValue: 0,
  },
  animationDuration: {
    description: 'Specifies the duration of animation, the unit of this option is ms.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'Animation',
      defaultValue: {
        summary: '1500',
      },
    },
    defaultValue: 1500,
  },
  animationEasing: {
    description: 'The type of easing function.',
    control: {
      type: 'select',
    },
    options: ['linear', 'ease', 'ease-in', 'ease-out', 'ease-in-out'],
    table: {
      type: {
        summary: '"ease" | "ease-in" | "ease-in-out" | "ease-out" | "linear"',
      },
      category: 'Animation',
      defaultValue: {
        summary: 'linear',
      },
    },
    defaultValue: 'linear',
  },
  animationId: {
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'Animation',
    },
    description: "@deprecated unused prop, doesn't do anything, use `key` instead",
  },
  aspectRatio: {
    description: "The treemap will try to keep every single rectangle's aspect ratio near the aspectRatio given.",
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
      defaultValue: {
        summary: '1.618033988749895',
      },
    },
    defaultValue: 1.618033988749895,
  },
  children: {
    table: {
      type: {
        summary: 'ReactNode',
      },
      category: 'General',
    },
  },
  className: {
    control: {
      type: 'text',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'Style',
    },
  },
  colorPanel: {
    control: {
      type: 'color',
    },
    table: {
      type: {
        summary: 'Array<string>',
      },
      category: 'General',
    },
  },
  content: {
    description:
      'If set to a React element, the option is the customized React element of rendering the content.\nIf set to a function, the function will be called to render the content.',
    table: {
      type: {
        summary: '(union of 8 variants)',
      },
      category: 'General',
    },
  },
  data: {
    description:
      'The source data. Each element should be an object.\nThe properties of each object represent the values of different data dimensions.\n\nUse the `dataKey` prop to specify which properties to use.\n\nIf the `children` property is present on an element, it will be treated as a nested treemap.',
    table: {
      type: {
        summary: 'Array<TreemapDataType>',
      },
      category: 'General',
    },
  },
  dataKey: {
    description:
      'Decides how to extract the value of this Treemap from the data:\n- `string`: the name of the field in the data object;\n- `number`: the index of the field in the data;\n- `function`: a function that receives the data object and returns the value of this Treemap.',
    table: {
      type: {
        summary: 'Function | number | string',
      },
      category: 'General',
      defaultValue: {
        summary: 'value',
      },
    },
    defaultValue: 'value',
  },
  fill: {
    control: {
      type: 'color',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'Style',
    },
  },
  height: {
    description: 'The height of chart container.\nCan be a number or a percent string like "100%".',
    table: {
      type: {
        summary: '`${number}%` | number',
      },
      category: 'General',
    },
  },
  id: {
    control: {
      type: 'text',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'General',
    },
  },
  isAnimationActive: {
    description:
      'If set false, animation of treemap will be disabled.\nIf set "auto", the animation will be disabled in SSR and enabled in browser.',
    table: {
      type: {
        summary: '"auto" | false | true',
      },
      category: 'Animation',
      defaultValue: {
        summary: 'auto',
      },
    },
    defaultValue: 'auto',
  },
  isUpdateAnimationActive: {
    table: {
      type: {
        summary: '"auto" | false | true',
      },
      category: 'Animation',
      defaultValue: {
        summary: 'auto',
      },
    },
    defaultValue: 'auto',
  },
  nameKey: {
    description:
      'Name represents each sector in the tooltip.\nThis allows you to extract the name from the data:\n\n- `string`: the name of the field in the data object;\n- `number`: the index of the field in the data;\n- `function`: a function that receives the data object and returns the name.',
    table: {
      type: {
        summary: 'Function | number | string',
      },
      category: 'General',
      defaultValue: {
        summary: 'name',
      },
    },
    defaultValue: 'name',
  },
  nestIndexContent: {
    table: {
      type: {
        summary: 'Function | ReactNode',
      },
      category: 'General',
    },
  },
  onAnimationEnd: {
    description: 'The customized event handler of animation end',
    table: {
      type: {
        summary: 'Function',
      },
      category: 'Events',
    },
  },
  onAnimationStart: {
    description: 'The customized event handler of animation start',
    table: {
      type: {
        summary: 'Function',
      },
      category: 'Events',
    },
  },
  onClick: {
    table: {
      type: {
        summary: 'Function',
      },
      category: 'Events',
    },
  },
  onMouseEnter: {
    table: {
      type: {
        summary: 'Function',
      },
      category: 'Events',
    },
  },
  onMouseLeave: {
    table: {
      type: {
        summary: 'Function',
      },
      category: 'Events',
    },
  },
  stroke: {
    control: {
      type: 'color',
    },
    table: {
      type: {
        summary: 'string',
      },
      category: 'Style',
    },
  },
  style: {
    table: {
      type: {
        summary: 'React.CSSProperties',
      },
      category: 'Style',
    },
  },
  throttleDelay: {
    description:
      "Decides the time interval to throttle events.\nOnly events defined in `throttledEvents` prop are throttled.\nAll other events are executed immediately/synchronously.\n\nOptions:\n- `number`: the time interval in milliseconds\n- `'raf'`: use requestAnimationFrame to schedule updates.",
    table: {
      type: {
        summary: '"raf" | number',
      },
      category: 'General',
      defaultValue: {
        summary: 'raf',
      },
    },
    defaultValue: 'raf',
  },
  throttledEvents: {
    description:
      "Defines which events should be throttled.\nEvents not in this list will not be throttled.\n\nUse the special value `'all'` to throttle all events. Empty array means no events are throttled.\n\nUse the prop `throttleDelay` to define the throttling interval.\n\nIf an event is on this list, then you lose the opportunity to access the event synchronously.\nWhich means that if you want to call `e.preventDefault()` or `e.stopPropagation()` inside the event handler,\nthen that event handler must not be in this list.",
    table: {
      type: {
        summary: '"all" | Array<keyof GlobalEventHandlersEventMap>',
      },
      category: 'General',
      defaultValue: {
        summary: '["mousemove","touchmove","pointermove","scroll","wheel"]',
      },
    },
    defaultValue: ['mousemove', 'touchmove', 'pointermove', 'scroll', 'wheel'],
  },
  type: {
    description:
      "The type of treemap to render.\n\n- 'flat': Renders the entire treemap at once, with all leaf nodes visible.\n- 'nest': Renders an interactive, nested treemap. Clicking on a parent node will \"zoom in\" to show its children,\n  and a breadcrumb navigation will be displayed to allow navigating back up the hierarchy.",
    table: {
      type: {
        summary: '"flat" | "nest"',
      },
      category: 'General',
      defaultValue: {
        summary: 'flat',
      },
    },
    defaultValue: 'flat',
  },
  width: {
    description: 'The width of chart container.\nCan be a number or a percent string like "100%".',
    table: {
      type: {
        summary: '`${number}%` | number',
      },
      category: 'General',
    },
  },
};
