/**
 * This file is auto-generated by generateStorybookArgsFromSource.ts
 * Do not edit manually.
 */
import { StorybookArgs } from '../../../StorybookArgs';

export const ZIndexLayerArgs: StorybookArgs = {
  children: {
    description:
      'The content to render inside this zIndex layer.\nUndefined children are allowed and will render nothing and will still report the zIndex to the portal system.',
    table: {
      type: {
        summary: 'ReactNode',
      },
      category: 'General',
    },
  },
  zIndex: {
    description:
      'Z-Index of this component and its children.\n\nThe higher the value, the more on top it will be rendered.\nComponents with higher zIndex will appear in front of components with lower zIndex.\n\nIf `undefined` or `0`, the content is rendered in the default layer without portals.',
    control: {
      type: 'number',
    },
    table: {
      type: {
        summary: 'number',
      },
      category: 'General',
    },
  },
};
