version: 2
updates:
  # Enable version updates for npm - production dependencies
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    # With npm workspaces, all dependencies (including workspace packages) are managed from the root
    directory: '/'
    # Check the npm registry for updates every day
    schedule:
      interval: 'daily'
    versioning-strategy: auto
    # add the 'dependencies' label to PRs
    labels:
      - 'dependencies'
    # max of 10 PRs at a time from dependabot
    open-pull-requests-limit: 10
    groups:
      babel:
        patterns:
          - '@babel*'
      playwright:
        patterns:
          - 'playwright'
          - '@playwright/experimental-ct-react'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - 'react-is'
          - '@types/react'
          - '@types/react-dom'
          - '@types/react-is'
      react-router:
        patterns:
          - 'react-router'
          - 'react-router-dom'
      storybook:
        patterns:
          - '@storybook*'
          - 'storybook'
      stryker:
        patterns:
          - '@stryker*'
      typescript-eslint:
        patterns:
          - 'typescript-eslint'
          - '@typescript-eslint*'
          - 'eslint-plugin-typescript*'
      vite:
        patterns:
          - 'vite'
          - '@vitejs/plugin-react'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'
