import { describe, it, expect } from 'vitest';
import { ReflectionKind } from 'typedoc';
import { getPropertiesOf, getPropsOf, getPublicSymbolNames } from './omnidoc';

describe('omnidoc', () => {
  it('should identify all exported symbols', async () => {
    expect(await getPublicSymbolNames()).toMatchInlineSnapshot(`
      [
        "Cell",
        "ErrorBar",
        "Funnel",
        "DefaultTooltipContentProps",
        "LegendPayload",
        "ResponsiveContainerProps",
        "TreemapProps",
        "ZAxisProps",
        "AreaProps",
        "BarProps",
        "BrushProps",
        "CartesianAxisProps",
        "CartesianGridProps",
        "CellProps",
        "ChartOffset",
        "CrossProps",
        "CurveProps",
        "CustomizedProps",
        "DefaultLegendContentProps",
        "DotItemDotProps",
        "DotProps",
        "ErrorBarProps",
        "FunnelProps",
        "FunnelTrapezoidItem",
        "LabelListProps",
        "LabelProps",
        "LayerProps",
        "LegendProps",
        "LegendType",
        "LineProps",
        "MouseHandlerDataParam",
        "PieLabel",
        "PieLabelRenderProps",
        "PieProps",
        "PieSectorDataItem",
        "PlotArea",
        "PolarAngleAxisProps",
        "PolarGridProps",
        "PolarRadiusAxisProps",
        "PolygonProps",
        "RadarProps",
        "RadialBarProps",
        "RectangleProps",
        "ReferenceAreaProps",
        "ReferenceDotProps",
        "ReferenceLineProps",
        "ScatterProps",
        "SectorProps",
        "SurfaceProps",
        "SymbolsProps",
        "TextProps",
        "TooltipContentProps",
        "TooltipProps",
        "TrapezoidProps",
        "XAxisProps",
        "YAxisProps",
        "Area",
        "AreaChart",
        "Bar",
        "BarChart",
        "CartesianAxis",
        "Cell",
        "ComposedChart",
        "Cross",
        "Curve",
        "Dot",
        "FunnelChart",
        "getNiceTickValues",
        "Global",
        "Layer",
        "Line",
        "LineChart",
        "PieChart",
        "Polygon",
        "RadarChart",
        "RadialBarChart",
        "Rectangle",
        "ResponsiveContainer",
        "Scatter",
        "ScatterChart",
        "Sector",
        "Surface",
        "Text",
        "Trapezoid",
        "XAxis",
        "YAxis",
        "Brush",
        "CartesianGrid",
        "Customized",
        "DefaultLegendContent",
        "DefaultTooltipContent",
        "Label",
        "LabelList",
        "Legend",
        "Pie",
        "PolarAngleAxis",
        "PolarGrid",
        "PolarRadiusAxis",
        "Radar",
        "RadialBar",
        "ReferenceArea",
        "ReferenceDot",
        "ReferenceLine",
        "Sankey",
        "SunburstChart",
        "Symbols",
        "Tooltip",
        "Treemap",
        "useActiveTooltipDataPoints",
        "useActiveTooltipLabel",
        "useChartHeight",
        "useChartWidth",
        "useMargin",
        "useOffset",
        "usePlotArea",
        "useXAxisDomain",
        "useYAxisDomain",
        "ZAxis",
      ]
    `);
  }, 10000);

  it('should filter symbols by kind', async () => {
    // this is a list of exported runtime objects, looks useful. Where is ZAxis though? Maybe ZAxis is a function.
    expect(await getPublicSymbolNames(ReflectionKind.Variable)).toMatchInlineSnapshot(`
      [
        "Area",
        "AreaChart",
        "Bar",
        "BarChart",
        "CartesianAxis",
        "Cell",
        "ComposedChart",
        "Cross",
        "Curve",
        "Dot",
        "FunnelChart",
        "getNiceTickValues",
        "Global",
        "Layer",
        "Line",
        "LineChart",
        "PieChart",
        "Polygon",
        "RadarChart",
        "RadialBarChart",
        "Rectangle",
        "ResponsiveContainer",
        "Scatter",
        "ScatterChart",
        "Sector",
        "Surface",
        "Text",
        "Trapezoid",
        "XAxis",
        "YAxis",
      ]
    `);
  });

  it('should return properties', async () => {
    // this is not entirely helpful for what we need to do
    expect(await getPropertiesOf('Funnel')).toMatchInlineSnapshot(`
      [
        "constructor",
        "context",
        "props",
        "refs",
        "state",
        "contextType",
        "defaultProps",
        "displayName",
        "componentDidCatch",
        "componentDidMount",
        "componentDidUpdate",
        "componentWillMount",
        "componentWillReceiveProps",
        "componentWillUnmount",
        "componentWillUpdate",
        "forceUpdate",
        "getSnapshotBeforeUpdate",
        "render",
        "setState",
        "shouldComponentUpdate",
        "UNSAFE_componentWillMount",
        "UNSAFE_componentWillReceiveProps",
        "UNSAFE_componentWillUpdate",
      ]
    `);
  });

  it('should return props', async () => {
    expect(await getPropsOf('ReferenceLine')).toMatchInlineSnapshot(`
      {
        "categories": undefined,
        "children": undefined,
        "childrenIncludingDocuments": undefined,
        "comment": {
          "blockTags": undefined,
          "label": undefined,
          "modifierTags": undefined,
          "summary": [
            {
              "kind": "text",
              "text": "This excludes ",
            },
            {
              "kind": "code",
              "text": "\`viewBox\`",
            },
            {
              "kind": "text",
              "text": " prop from svg for two reasons:
      1. The components wants viewBox of object type, and svg wants string
         - so there's a conflict, and the component will throw if it gets string
      2. Internally the component calls ",
            },
            {
              "kind": "code",
              "text": "\`svgPropertiesNoEvents\`",
            },
            {
              "kind": "text",
              "text": " which filters the viewBox away anyway",
            },
          ],
        },
        "defaultValue": undefined,
        "documents": undefined,
        "extendedBy": undefined,
        "extendedTypes": undefined,
        "flags": {},
        "getSignature": undefined,
        "groups": undefined,
        "id": 226,
        "implementationOf": undefined,
        "implementedBy": undefined,
        "implementedTypes": undefined,
        "indexSignatures": undefined,
        "inheritedFrom": undefined,
        "kind": 2097152,
        "name": "ReferenceLineProps",
        "overwrites": undefined,
        "packageVersion": undefined,
        "readme": undefined,
        "setSignature": undefined,
        "signatures": undefined,
        "sources": [
          {
            "character": 12,
            "fileName": "src/cartesian/ReferenceLine.tsx",
            "line": 110,
            "url": "https://github.com/recharts/recharts/blob/5fd1d87ed09026a681beaaae53c9541fb0ce5317/src/cartesian/ReferenceLine.tsx#L110",
          },
        ],
        "type": {
          "type": "intersection",
          "types": [
            {
              "externalUrl": undefined,
              "name": "Omit",
              "package": "typescript",
              "target": {
                "packageName": "typescript",
                "packagePath": "lib/lib.es5.d.ts",
                "qualifiedName": "Omit",
              },
              "type": "reference",
              "typeArguments": [
                {
                  "externalUrl": undefined,
                  "name": "SVGProps",
                  "package": "@types/react",
                  "qualifiedName": "React.SVGProps",
                  "target": {
                    "packageName": "@types/react",
                    "packagePath": "index.d.ts",
                    "qualifiedName": "React.SVGProps",
                  },
                  "type": "reference",
                  "typeArguments": [
                    {
                      "externalUrl": undefined,
                      "name": "SVGLineElement",
                      "package": "typescript",
                      "target": {
                        "packageName": "typescript",
                        "packagePath": "lib/lib.dom.d.ts",
                        "qualifiedName": "SVGLineElement",
                      },
                      "type": "reference",
                      "typeArguments": undefined,
                    },
                  ],
                },
                {
                  "type": "literal",
                  "value": "viewBox",
                },
              ],
            },
            {
              "declaration": {
                "categories": undefined,
                "children": [
                  {
                    "categories": undefined,
                    "children": undefined,
                    "childrenIncludingDocuments": undefined,
                    "comment": undefined,
                    "defaultValue": undefined,
                    "documents": undefined,
                    "extendedBy": undefined,
                    "extendedTypes": undefined,
                    "flags": {
                      "isOptional": true,
                    },
                    "getSignature": undefined,
                    "groups": undefined,
                    "id": 233,
                    "implementationOf": undefined,
                    "implementedBy": undefined,
                    "implementedTypes": undefined,
                    "indexSignatures": undefined,
                    "inheritedFrom": undefined,
                    "kind": 1024,
                    "name": "className",
                    "overwrites": undefined,
                    "packageVersion": undefined,
                    "readme": undefined,
                    "setSignature": undefined,
                    "signatures": undefined,
                    "sources": [
                      {
                        "character": 2,
                        "fileName": "src/cartesian/ReferenceLine.tsx",
                        "line": 97,
                        "url": "https://github.com/recharts/recharts/blob/5fd1d87ed09026a681beaaae53c9541fb0ce5317/src/cartesian/ReferenceLine.tsx#L97",
                      },
                    ],
                    "type": {
                      "elementSummaries": undefined,
                      "type": "union",
                      "types": [
                        {
                          "name": "string",
                          "type": "intrinsic",
                        },
                        {
                          "name": "number",
                          "type": "intrinsic",
                        },
                      ],
                    },
                    "typeParameters": undefined,
                    "variant": "declaration",
                  },
                  {
                    "categories": undefined,
                    "children": undefined,
                    "childrenIncludingDocuments": undefined,
                    "comment": undefined,
                    "defaultValue": undefined,
                    "documents": undefined,
                    "extendedBy": undefined,
                    "extendedTypes": undefined,
                    "flags": {
                      "isOptional": true,
                    },
                    "getSignature": undefined,
                    "groups": undefined,
                    "id": 228,
                    "implementationOf": undefined,
                    "implementedBy": undefined,
                    "implementedTypes": undefined,
                    "indexSignatures": undefined,
                    "inheritedFrom": undefined,
                    "kind": 1024,
                    "name": "ifOverflow",
                    "overwrites": undefined,
                    "packageVersion": undefined,
                    "readme": undefined,
                    "setSignature": undefined,
                    "signatures": undefined,
                    "sources": [
                      {
                        "character": 2,
                        "fileName": "src/cartesian/ReferenceLine.tsx",
                        "line": 46,
                        "url": "https://github.com/recharts/recharts/blob/5fd1d87ed09026a681beaaae53c9541fb0ce5317/src/cartesian/ReferenceLine.tsx#L46",
                      },
                    ],
                    "type": {
                      "externalUrl": undefined,
                      "name": "IfOverflow",
                      "package": "recharts",
                      "target": {
                        "packageName": "recharts",
                        "packagePath": "src/util/IfOverflow.ts",
                        "qualifiedName": "IfOverflow",
                      },
                      "type": "reference",
                      "typeArguments": undefined,
                    },
                    "typeParameters": undefined,
                    "variant": "declaration",
                  },
                  {
                    "categories": undefined,
                    "children": undefined,
                    "childrenIncludingDocuments": undefined,
                    "comment": undefined,
                    "defaultValue": undefined,
                    "documents": undefined,
                    "extendedBy": undefined,
                    "extendedTypes": undefined,
                    "flags": {
                      "isOptional": true,
                    },
                    "getSignature": undefined,
                    "groups": undefined,
                    "id": 240,
                    "implementationOf": undefined,
                    "implementedBy": undefined,
                    "implementedTypes": undefined,
                    "indexSignatures": undefined,
                    "inheritedFrom": undefined,
                    "kind": 1024,
                    "name": "label",
                    "overwrites": undefined,
                    "packageVersion": undefined,
                    "readme": undefined,
                    "setSignature": undefined,
                    "signatures": undefined,
                    "sources": [
                      {
                        "character": 2,
                        "fileName": "src/cartesian/ReferenceLine.tsx",
                        "line": 101,
                        "url": "https://github.com/recharts/recharts/blob/5fd1d87ed09026a681beaaae53c9541fb0ce5317/src/cartesian/ReferenceLine.tsx#L101",
                      },
                    ],
                    "type": {
                      "externalUrl": undefined,
                      "name": "ImplicitLabelType",
                      "package": "recharts",
                      "target": {
                        "packageName": "recharts",
                        "packagePath": "src/component/Label.tsx",
                        "qualifiedName": "ImplicitLabelType",
                      },
                      "type": "reference",
                      "typeArguments": undefined,
                    },
                    "typeParameters": undefined,
                    "variant": "declaration",
                  },
                  {
                    "categories": undefined,
                    "children": undefined,
                    "childrenIncludingDocuments": undefined,
                    "comment": {
                      "blockTags": undefined,
                      "label": undefined,
                      "modifierTags": undefined,
                      "summary": [
                        {
                          "kind": "text",
                          "text": "The position of the reference line when the axis has bandwidth
      (e.g., a band scale). This determines where within the band
      the line is drawn.",
                        },
                      ],
                    },
                    "defaultValue": undefined,
                    "documents": undefined,
                    "extendedBy": undefined,
                    "extendedTypes": undefined,
                    "flags": {
                      "isOptional": true,
                    },
                    "getSignature": undefined,
                    "groups": undefined,
                    "id": 232,
                    "implementationOf": undefined,
                    "implementedBy": undefined,
                    "implementedTypes": undefined,
                    "indexSignatures": undefined,
                    "inheritedFrom": undefined,
                    "kind": 1024,
                    "name": "position",
                    "overwrites": undefined,
                    "packageVersion": undefined,
                    "readme": undefined,
                    "setSignature": undefined,
                    "signatures": undefined,
                    "sources": [
                      {
                        "character": 2,
                        "fileName": "src/cartesian/ReferenceLine.tsx",
                        "line": 95,
                        "url": "https://github.com/recharts/recharts/blob/5fd1d87ed09026a681beaaae53c9541fb0ce5317/src/cartesian/ReferenceLine.tsx#L95",
                      },
                    ],
                    "type": {
                      "externalUrl": undefined,
                      "name": "ReferenceLinePosition",
                      "package": "recharts",
                      "target": {
                        "packageName": "recharts",
                        "packagePath": "src/cartesian/ReferenceLine.tsx",
                        "qualifiedName": "ReferenceLinePosition",
                      },
                      "type": "reference",
                      "typeArguments": undefined,
                    },
                    "typeParameters": undefined,
                    "variant": "declaration",
                  },
                  {
                    "categories": undefined,
                    "children": undefined,
                    "childrenIncludingDocuments": undefined,
                    "comment": {
                      "blockTags": undefined,
                      "label": undefined,
                      "modifierTags": undefined,
                      "summary": [
                        {
                          "kind": "text",
                          "text": "An array of two points that define the start and end of a line segment.
      Each point is an object with ",
                        },
                        {
                          "kind": "code",
                          "text": "\`x\`",
                        },
                        {
                          "kind": "text",
                          "text": " and ",
                        },
                        {
                          "kind": "code",
                          "text": "\`y\`",
                        },
                        {
                          "kind": "text",
                          "text": " properties.
      If this array has other than two points, it will be ignored.

      These coordinates are in data space, meaning that you should provide
      values that correspond to the data domain of the axes.
      So you would provide a value of ",
                        },
                        {
                          "kind": "code",
                          "text": "\`Page A\`",
                        },
                        {
                          "kind": "text",
                          "text": " to indicate the data value ",
                        },
                        {
                          "kind": "code",
                          "text": "\`Page A\`",
                        },
                        {
                          "kind": "text",
                          "text": "
      and then recharts will convert that to pixels.

      Likewise for numbers. If your x-axis goes from 0 to 100,
      and you want the line to end at 50, you would provide ",
                        },
                        {
                          "kind": "code",
                          "text": "\`50\`",
                        },
                        {
                          "kind": "text",
                          "text": " here.

      This prop is only used if both ",
                        },
                        {
                          "kind": "code",
                          "text": "\`x\`",
                        },
                        {
                          "kind": "text",
                          "text": " and ",
                        },
                        {
                          "kind": "code",
                          "text": "\`y\`",
                        },
                        {
                          "kind": "text",
                          "text": " props are undefined.",
                        },
                      ],
                    },
                    "defaultValue": undefined,
                    "documents": undefined,
                    "extendedBy": undefined,
                    "extendedTypes": undefined,
                    "flags": {
                      "isOptional": true,
                    },
                    "getSignature": undefined,
                    "groups": undefined,
                    "id": 231,
                    "implementationOf": undefined,
                    "implementedBy": undefined,
                    "implementedTypes": undefined,
                    "indexSignatures": undefined,
                    "inheritedFrom": undefined,
                    "kind": 1024,
                    "name": "segment",
                    "overwrites": undefined,
                    "packageVersion": undefined,
                    "readme": undefined,
                    "setSignature": undefined,
                    "signatures": undefined,
                    "sources": [
                      {
                        "character": 2,
                        "fileName": "src/cartesian/ReferenceLine.tsx",
                        "line": 88,
                        "url": "https://github.com/recharts/recharts/blob/5fd1d87ed09026a681beaaae53c9541fb0ce5317/src/cartesian/ReferenceLine.tsx#L88",
                      },
                    ],
                    "type": {
                      "operator": "readonly",
                      "target": {
                        "elementType": {
                          "externalUrl": undefined,
                          "name": "Segment",
                          "package": "recharts",
                          "target": {
                            "packageName": "recharts",
                            "packagePath": "src/cartesian/ReferenceLine.tsx",
                            "qualifiedName": "Segment",
                          },
                          "type": "reference",
                          "typeArguments": undefined,
                        },
                        "type": "array",
                      },
                      "type": "typeOperator",
                    },
                    "typeParameters": undefined,
                    "variant": "declaration",
                  },
                  {
                    "categories": undefined,
                    "children": undefined,
                    "childrenIncludingDocuments": undefined,
                    "comment": undefined,
                    "defaultValue": undefined,
                    "documents": undefined,
                    "extendedBy": undefined,
                    "extendedTypes": undefined,
                    "flags": {
                      "isOptional": true,
                    },
                    "getSignature": undefined,
                    "groups": undefined,
                    "id": 236,
                    "implementationOf": undefined,
                    "implementedBy": undefined,
                    "implementedTypes": undefined,
                    "indexSignatures": undefined,
                    "inheritedFrom": undefined,
                    "kind": 1024,
                    "name": "shape",
                    "overwrites": undefined,
                    "packageVersion": undefined,
                    "readme": undefined,
                    "setSignature": undefined,
                    "signatures": undefined,
                    "sources": [
                      {
                        "character": 2,
                        "fileName": "src/cartesian/ReferenceLine.tsx",
                        "line": 100,
                        "url": "https://github.com/recharts/recharts/blob/5fd1d87ed09026a681beaaae53c9541fb0ce5317/src/cartesian/ReferenceLine.tsx#L100",
                      },
                    ],
                    "type": {
                      "elementSummaries": undefined,
                      "type": "union",
                      "types": [
                        {
                          "externalUrl": undefined,
                          "name": "ReactElement",
                          "package": "@types/react",
                          "qualifiedName": "React.ReactElement",
                          "target": {
                            "packageName": "@types/react",
                            "packagePath": "index.d.ts",
                            "qualifiedName": "React.ReactElement",
                          },
                          "type": "reference",
                          "typeArguments": [
                            {
                              "externalUrl": undefined,
                              "name": "SVGElement",
                              "package": "typescript",
                              "target": {
                                "packageName": "typescript",
                                "packagePath": "lib/lib.dom.d.ts",
                                "qualifiedName": "SVGElement",
                              },
                              "type": "reference",
                              "typeArguments": undefined,
                            },
                            {
                              "elementSummaries": undefined,
                              "type": "union",
                              "types": [
                                {
                                  "name": "string",
                                  "type": "intrinsic",
                                },
                                {
                                  "externalUrl": undefined,
                                  "name": "JSXElementConstructor",
                                  "package": "@types/react",
                                  "qualifiedName": "React.JSXElementConstructor",
                                  "target": {
                                    "packageName": "@types/react",
                                    "packagePath": "index.d.ts",
                                    "qualifiedName": "React.JSXElementConstructor",
                                  },
                                  "type": "reference",
                                  "typeArguments": [
                                    {
                                      "name": "any",
                                      "type": "intrinsic",
                                    },
                                  ],
                                },
                              ],
                            },
                          ],
                        },
                        {
                          "declaration": {
                            "categories": undefined,
                            "children": undefined,
                            "childrenIncludingDocuments": undefined,
                            "comment": undefined,
                            "defaultValue": undefined,
                            "documents": undefined,
                            "extendedBy": undefined,
                            "extendedTypes": undefined,
                            "flags": {},
                            "getSignature": undefined,
                            "groups": undefined,
                            "id": 237,
                            "implementationOf": undefined,
                            "implementedBy": undefined,
                            "implementedTypes": undefined,
                            "indexSignatures": undefined,
                            "inheritedFrom": undefined,
                            "kind": 65536,
                            "name": "__type",
                            "overwrites": undefined,
                            "packageVersion": undefined,
                            "readme": undefined,
                            "setSignature": undefined,
                            "signatures": [
                              {
                                "comment": undefined,
                                "flags": {},
                                "id": 238,
                                "implementationOf": undefined,
                                "inheritedFrom": undefined,
                                "kind": 4096,
                                "name": "__type",
                                "overwrites": undefined,
                                "parameters": [
                                  {
                                    "comment": undefined,
                                    "defaultValue": undefined,
                                    "flags": {},
                                    "id": 239,
                                    "kind": 32768,
                                    "name": "props",
                                    "type": {
                                      "name": "any",
                                      "type": "intrinsic",
                                    },
                                    "variant": "param",
                                  },
                                ],
                                "sources": [
                                  {
                                    "character": 38,
                                    "fileName": "src/cartesian/ReferenceLine.tsx",
                                    "line": 100,
                                    "url": "https://github.com/recharts/recharts/blob/5fd1d87ed09026a681beaaae53c9541fb0ce5317/src/cartesian/ReferenceLine.tsx#L100",
                                  },
                                ],
                                "type": {
                                  "externalUrl": undefined,
                                  "name": "ReactElement",
                                  "package": "@types/react",
                                  "qualifiedName": "React.ReactElement",
                                  "target": {
                                    "packageName": "@types/react",
                                    "packagePath": "index.d.ts",
                                    "qualifiedName": "React.ReactElement",
                                  },
                                  "type": "reference",
                                  "typeArguments": [
                                    {
                                      "externalUrl": undefined,
                                      "name": "SVGElement",
                                      "package": "typescript",
                                      "target": {
                                        "packageName": "typescript",
                                        "packagePath": "lib/lib.dom.d.ts",
                                        "qualifiedName": "SVGElement",
                                      },
                                      "type": "reference",
                                      "typeArguments": undefined,
                                    },
                                  ],
                                },
                                "typeParameters": undefined,
                                "variant": "signature",
                              },
                            ],
                            "sources": [
                              {
                                "character": 38,
                                "fileName": "src/cartesian/ReferenceLine.tsx",
                                "line": 100,
                                "url": "https://github.com/recharts/recharts/blob/5fd1d87ed09026a681beaaae53c9541fb0ce5317/src/cartesian/ReferenceLine.tsx#L100",
                              },
                            ],
                            "type": undefined,
                            "typeParameters": undefined,
                            "variant": "declaration",
                          },
                          "type": "reflection",
                        },
                      ],
                    },
                    "typeParameters": undefined,
                    "variant": "declaration",
                  },
                  {
                    "categories": undefined,
                    "children": undefined,
                    "childrenIncludingDocuments": undefined,
                    "comment": {
                      "blockTags": undefined,
                      "label": undefined,
                      "modifierTags": undefined,
                      "summary": [
                        {
                          "kind": "text",
                          "text": "The x-coordinate of the reference line in data space.
      This value is used when you want to draw a vertical reference line.

      You should provide a value that corresponds to the data domain of the x-axis.
      So you would provide a value of ",
                        },
                        {
                          "kind": "code",
                          "text": "\`Page A\`",
                        },
                        {
                          "kind": "text",
                          "text": " to indicate the data value ",
                        },
                        {
                          "kind": "code",
                          "text": "\`Page A\`",
                        },
                        {
                          "kind": "text",
                          "text": "
      and then recharts will convert that to pixels.

      This prop is ignored if the ",
                        },
                        {
                          "kind": "code",
                          "text": "\`y\`",
                        },
                        {
                          "kind": "text",
                          "text": " prop is provided.
      If you provide this prop, then the ",
                        },
                        {
                          "kind": "code",
                          "text": "\`segment\`",
                        },
                        {
                          "kind": "text",
                          "text": " prop will be ignored.",
                        },
                      ],
                    },
                    "defaultValue": undefined,
                    "documents": undefined,
                    "extendedBy": undefined,
                    "extendedTypes": undefined,
                    "flags": {
                      "isOptional": true,
                    },
                    "getSignature": undefined,
                    "groups": undefined,
                    "id": 230,
                    "implementationOf": undefined,
                    "implementedBy": undefined,
                    "implementedTypes": undefined,
                    "indexSignatures": undefined,
                    "inheritedFrom": undefined,
                    "kind": 1024,
                    "name": "x",
                    "overwrites": undefined,
                    "packageVersion": undefined,
                    "readme": undefined,
                    "setSignature": undefined,
                    "signatures": undefined,
                    "sources": [
                      {
                        "character": 2,
                        "fileName": "src/cartesian/ReferenceLine.tsx",
                        "line": 71,
                        "url": "https://github.com/recharts/recharts/blob/5fd1d87ed09026a681beaaae53c9541fb0ce5317/src/cartesian/ReferenceLine.tsx#L71",
                      },
                    ],
                    "type": {
                      "elementSummaries": undefined,
                      "type": "union",
                      "types": [
                        {
                          "name": "string",
                          "type": "intrinsic",
                        },
                        {
                          "name": "number",
                          "type": "intrinsic",
                        },
                      ],
                    },
                    "typeParameters": undefined,
                    "variant": "declaration",
                  },
                  {
                    "categories": undefined,
                    "children": undefined,
                    "childrenIncludingDocuments": undefined,
                    "comment": undefined,
                    "defaultValue": undefined,
                    "documents": undefined,
                    "extendedBy": undefined,
                    "extendedTypes": undefined,
                    "flags": {
                      "isOptional": true,
                    },
                    "getSignature": undefined,
                    "groups": undefined,
                    "id": 235,
                    "implementationOf": undefined,
                    "implementedBy": undefined,
                    "implementedTypes": undefined,
                    "indexSignatures": undefined,
                    "inheritedFrom": undefined,
                    "kind": 1024,
                    "name": "xAxisId",
                    "overwrites": undefined,
                    "packageVersion": undefined,
                    "readme": undefined,
                    "setSignature": undefined,
                    "signatures": undefined,
                    "sources": [
                      {
                        "character": 2,
                        "fileName": "src/cartesian/ReferenceLine.tsx",
                        "line": 99,
                        "url": "https://github.com/recharts/recharts/blob/5fd1d87ed09026a681beaaae53c9541fb0ce5317/src/cartesian/ReferenceLine.tsx#L99",
                      },
                    ],
                    "type": {
                      "elementSummaries": undefined,
                      "type": "union",
                      "types": [
                        {
                          "name": "string",
                          "type": "intrinsic",
                        },
                        {
                          "name": "number",
                          "type": "intrinsic",
                        },
                      ],
                    },
                    "typeParameters": undefined,
                    "variant": "declaration",
                  },
                  {
                    "categories": undefined,
                    "children": undefined,
                    "childrenIncludingDocuments": undefined,
                    "comment": {
                      "blockTags": undefined,
                      "label": undefined,
                      "modifierTags": undefined,
                      "summary": [
                        {
                          "kind": "text",
                          "text": "The y-coordinate of the reference line in data space.
      This value is used when you want to draw a horizontal reference line.

      You should provide a value that corresponds to the data domain of the y-axis.
      So you would provide a value of ",
                        },
                        {
                          "kind": "code",
                          "text": "\`100\`",
                        },
                        {
                          "kind": "text",
                          "text": " to indicate the data value ",
                        },
                        {
                          "kind": "code",
                          "text": "\`100\`",
                        },
                        {
                          "kind": "text",
                          "text": "
      and then recharts will convert that to pixels.

      If you provide this prop, then the ",
                        },
                        {
                          "kind": "code",
                          "text": "\`x\`",
                        },
                        {
                          "kind": "text",
                          "text": " and ",
                        },
                        {
                          "kind": "code",
                          "text": "\`segment\`",
                        },
                        {
                          "kind": "text",
                          "text": " props will be ignored.",
                        },
                      ],
                    },
                    "defaultValue": undefined,
                    "documents": undefined,
                    "extendedBy": undefined,
                    "extendedTypes": undefined,
                    "flags": {
                      "isOptional": true,
                    },
                    "getSignature": undefined,
                    "groups": undefined,
                    "id": 229,
                    "implementationOf": undefined,
                    "implementedBy": undefined,
                    "implementedTypes": undefined,
                    "indexSignatures": undefined,
                    "inheritedFrom": undefined,
                    "kind": 1024,
                    "name": "y",
                    "overwrites": undefined,
                    "packageVersion": undefined,
                    "readme": undefined,
                    "setSignature": undefined,
                    "signatures": undefined,
                    "sources": [
                      {
                        "character": 2,
                        "fileName": "src/cartesian/ReferenceLine.tsx",
                        "line": 58,
                        "url": "https://github.com/recharts/recharts/blob/5fd1d87ed09026a681beaaae53c9541fb0ce5317/src/cartesian/ReferenceLine.tsx#L58",
                      },
                    ],
                    "type": {
                      "elementSummaries": undefined,
                      "type": "union",
                      "types": [
                        {
                          "name": "string",
                          "type": "intrinsic",
                        },
                        {
                          "name": "number",
                          "type": "intrinsic",
                        },
                      ],
                    },
                    "typeParameters": undefined,
                    "variant": "declaration",
                  },
                  {
                    "categories": undefined,
                    "children": undefined,
                    "childrenIncludingDocuments": undefined,
                    "comment": undefined,
                    "defaultValue": undefined,
                    "documents": undefined,
                    "extendedBy": undefined,
                    "extendedTypes": undefined,
                    "flags": {
                      "isOptional": true,
                    },
                    "getSignature": undefined,
                    "groups": undefined,
                    "id": 234,
                    "implementationOf": undefined,
                    "implementedBy": undefined,
                    "implementedTypes": undefined,
                    "indexSignatures": undefined,
                    "inheritedFrom": undefined,
                    "kind": 1024,
                    "name": "yAxisId",
                    "overwrites": undefined,
                    "packageVersion": undefined,
                    "readme": undefined,
                    "setSignature": undefined,
                    "signatures": undefined,
                    "sources": [
                      {
                        "character": 2,
                        "fileName": "src/cartesian/ReferenceLine.tsx",
                        "line": 98,
                        "url": "https://github.com/recharts/recharts/blob/5fd1d87ed09026a681beaaae53c9541fb0ce5317/src/cartesian/ReferenceLine.tsx#L98",
                      },
                    ],
                    "type": {
                      "elementSummaries": undefined,
                      "type": "union",
                      "types": [
                        {
                          "name": "string",
                          "type": "intrinsic",
                        },
                        {
                          "name": "number",
                          "type": "intrinsic",
                        },
                      ],
                    },
                    "typeParameters": undefined,
                    "variant": "declaration",
                  },
                  {
                    "categories": undefined,
                    "children": undefined,
                    "childrenIncludingDocuments": undefined,
                    "comment": {
                      "blockTags": [
                        {
                          "content": [
                            {
                              "kind": "text",
                              "text": "3.4",
                            },
                          ],
                          "name": undefined,
                          "tag": "@since",
                          "typeAnnotation": undefined,
                        },
                        {
                          "content": [
                            {
                              "kind": "code",
                              "text": "\`\`\`ts
      0
      \`\`\`",
                            },
                          ],
                          "name": undefined,
                          "tag": "@defaultValue",
                          "typeAnnotation": undefined,
                        },
                      ],
                      "label": undefined,
                      "modifierTags": undefined,
                      "summary": [
                        {
                          "kind": "text",
                          "text": "Z-Index of this component and its children. The higher the value,
      the more on top it will be rendered.
      Components with higher zIndex will appear in front of components with lower zIndex.",
                        },
                      ],
                    },
                    "defaultValue": undefined,
                    "documents": undefined,
                    "extendedBy": undefined,
                    "extendedTypes": undefined,
                    "flags": {
                      "isOptional": true,
                    },
                    "getSignature": undefined,
                    "groups": undefined,
                    "id": 241,
                    "implementationOf": undefined,
                    "implementedBy": undefined,
                    "implementedTypes": undefined,
                    "indexSignatures": undefined,
                    "inheritedFrom": undefined,
                    "kind": 1024,
                    "name": "zIndex",
                    "overwrites": undefined,
                    "packageVersion": undefined,
                    "readme": undefined,
                    "setSignature": undefined,
                    "signatures": undefined,
                    "sources": [
                      {
                        "character": 2,
                        "fileName": "src/zindex/ZIndexLayer.tsx",
                        "line": 22,
                        "url": "https://github.com/recharts/recharts/blob/5fd1d87ed09026a681beaaae53c9541fb0ce5317/src/zindex/ZIndexLayer.tsx#L22",
                      },
                    ],
                    "type": {
                      "name": "number",
                      "type": "intrinsic",
                    },
                    "typeParameters": undefined,
                    "variant": "declaration",
                  },
                ],
                "childrenIncludingDocuments": undefined,
                "comment": undefined,
                "defaultValue": undefined,
                "documents": undefined,
                "extendedBy": undefined,
                "extendedTypes": undefined,
                "flags": {},
                "getSignature": undefined,
                "groups": [
                  {
                    "categories": undefined,
                    "children": [
                      233,
                      228,
                      240,
                      232,
                      231,
                      236,
                      230,
                      235,
                      229,
                      234,
                      241,
                    ],
                    "description": undefined,
                    "title": "Properties",
                  },
                ],
                "id": 227,
                "implementationOf": undefined,
                "implementedBy": undefined,
                "implementedTypes": undefined,
                "indexSignatures": undefined,
                "inheritedFrom": undefined,
                "kind": 65536,
                "name": "__type",
                "overwrites": undefined,
                "packageVersion": undefined,
                "readme": undefined,
                "setSignature": undefined,
                "signatures": undefined,
                "sources": [
                  {
                    "character": 10,
                    "fileName": "src/cartesian/ReferenceLine.tsx",
                    "line": 45,
                    "url": "https://github.com/recharts/recharts/blob/5fd1d87ed09026a681beaaae53c9541fb0ce5317/src/cartesian/ReferenceLine.tsx#L45",
                  },
                ],
                "type": undefined,
                "typeParameters": undefined,
                "variant": "declaration",
              },
              "type": "reflection",
            },
          ],
        },
        "typeParameters": undefined,
        "variant": "declaration",
      }
    `);
  });
});
