import { describe, expect, it, test } from 'vitest';
import { shallowEqual } from 'react-redux';
import { ProjectDocReader } from './readProject';
import { ApiDocReader } from './readApiDoc';
import { StorybookDocReader } from './readStorybookDoc';
import { DefaultValue } from './DocReader';
import { isNotNil } from '../src/util/DataUtils';
import { normalizeText } from './util/normalizeText';
import { coloredDiff } from './util/coloredDiff';
import { componentsExcludedFromOmnidoc } from './componentsExcludedFromOmnidoc';
import { OMNIDOC_AUTOMATED_API_DOCS_COMPONENTS } from './generateApiDoc';
import { apiCates } from '../www/src/docs/apiCates';
import { allApiDocs } from '../www/src/docs/api/index';
import { STORYBOOK_AUTOMATED_ARG_COMPONENTS } from './generateStorybookArgs';

describe('omnidoc - documentation consistency', () => {
  const projectReader = new ProjectDocReader();
  const apiDocReader = new ApiDocReader();
  const storybookReader = new StorybookDocReader();

  it('if it is documented then it must actually exist in the project', () => {
    const projectSymbols = new Set(projectReader.getAllRuntimeExportedNames());
    const apiDocSymbols = apiDocReader.getPublicSymbolNames();

    const missingInProject: string[] = [];

    for (const symbol of apiDocSymbols) {
      if (!projectSymbols.has(symbol)) {
        missingInProject.push(symbol);
      }
    }

    if (missingInProject.length > 0) {
      console.error(
        `Found ${missingInProject.length} symbol(s) documented in API docs but not exported from the project:`,
        missingInProject,
      );
    }

    expect(missingInProject).toEqual([]);
  });

  it('should have autogenerated API docs for each exports that is not a type', () => {
    const projectSymbols = new Set(projectReader.getAllRuntimeExportedNames());
    for (const symbol of projectSymbols) {
      expect(allApiDocs).toHaveProperty(symbol);
    }
  });

  it('should have a mapping defined in apiCates for each export because without this mapping, navigation will not render a link', () => {
    const componentsThatHaveApiCategoryMapping = apiCates.flatMap(cat => cat.items);

    for (const symbol of projectReader.getAllRuntimeExportedNames()) {
      expect(componentsThatHaveApiCategoryMapping).toContain(symbol);
    }
  });

  it('all Storybook symbols must exist in the project', () => {
    const projectSymbols = new Set(projectReader.getPublicSymbolNames());
    const storybookSymbols = storybookReader.getPublicSymbolNames();

    const missingInProject: string[] = [];

    for (const symbol of storybookSymbols) {
      if (!projectSymbols.has(symbol)) {
        missingInProject.push(symbol);
      }
    }

    if (missingInProject.length > 0) {
      console.error(
        `Found ${missingInProject.length} symbol(s) documented in Storybook but not exported from the project:`,
        missingInProject,
      );
    }

    expect(missingInProject).toEqual([]);
  });

  it('all API doc props must exist in the project', () => {
    const apiDocSymbols = apiDocReader
      .getPublicComponentNames()
      /*
       * Filter out components that are auto-generated because those are guaranteed to match
       */
      .filter(name => !OMNIDOC_AUTOMATED_API_DOCS_COMPONENTS.includes(name));
    const missingProps: Array<string> = [];

    for (const component of apiDocSymbols) {
      const apiDocProps = apiDocReader.getRechartsPropsOf(component);
      /*
       * Here we intentionally get all props including SVG inherited ones.
       * It's okay to document SVG props on recharts website!
       */
      const projectProps = new Set(projectReader.getAllPropsOf(component));

      for (const prop of apiDocProps) {
        if (!projectProps.has(prop)) {
          missingProps.push(
            `Component "${component}" has documented prop "${prop}" but that does not exist in the project.`,
          );
        }
      }
    }

    expect(missingProps).toEqual([]);
  });

  it('all Storybook props must exist in the project', () => {
    const storybookSymbols = storybookReader.getPublicComponentNames();
    const missingProps: Array<{ component: string; prop: string }> = [];

    for (const component of storybookSymbols) {
      const storybookProps = storybookReader.getRechartsPropsOf(component);
      /*
       * Here we intentionally get all props including SVG inherited ones.
       * It's okay to document SVG props on storybook!
       */
      const projectProps = new Set(projectReader.getAllPropsOf(component));

      for (const prop of storybookProps) {
        if (!projectProps.has(prop)) {
          missingProps.push({ component, prop });
        }
      }
    }

    expect(missingProps).toEqual([]);
  });

  describe('default props consistency', () => {
    function stringify(value: unknown): string {
      if (typeof value === 'string') {
        return value;
      }
      try {
        return JSON.stringify(value);
      } catch {
        return String(value);
      }
    }

    function stringifyDefaultValue(defaultValue: DefaultValue): DefaultValue {
      if (defaultValue.type === 'known') {
        return {
          type: 'known',
          value: stringify(defaultValue.value),
        };
      }
      return defaultValue;
    }

    function stripQuotes(str: unknown) {
      if (typeof str === 'string') {
        return str.replace(/^['"]|['"]$/g, '');
      }
      return stringify(str);
    }

    function compareValues(val1: unknown, val2: unknown) {
      if (typeof val1 === 'object' && typeof val2 === 'object') {
        return shallowEqual(val1, val2);
      }
      return stripQuotes(val1) === stripQuotes(val2);
    }

    function compareDefaultValues(
      documentedDefaultValue: DefaultValue,
      actualDefaultValue: DefaultValue,
    ): string | null {
      if (documentedDefaultValue.type === 'unreadable' || actualDefaultValue.type === 'unreadable') {
        return null;
      }
      if (documentedDefaultValue.type === 'known' && actualDefaultValue.type === 'known') {
        if (!compareValues(documentedDefaultValue.value, actualDefaultValue.value)) {
          return `Documented default value "${documentedDefaultValue.value}" [${typeof documentedDefaultValue.value}], but actually in project it is "${stringify(actualDefaultValue.value)}" [${typeof actualDefaultValue.value}]`;
        }
        return null;
      }
      if (documentedDefaultValue.type === 'none' && actualDefaultValue.type !== 'none') {
        return `Default value is ${actualDefaultValue.value} but it is not documented`;
      }
      if (documentedDefaultValue.type !== 'none' && actualDefaultValue.type === 'none') {
        return `Documented default value ${documentedDefaultValue.value}, but actually none exists in the project`;
      }
      return null;
    }

    test.each(
      apiDocReader
        .getPublicComponentNames()
        /*
         * Filter out components that are auto-generated because those are guaranteed to match
         */
        .filter(name => !OMNIDOC_AUTOMATED_API_DOCS_COMPONENTS.includes(name)),
    )('if %s has default props in the API, then that default value must be the same as in the project', component => {
      const allProps = apiDocReader.getRechartsPropsOf(component);
      const missingDefaultProps: string[] = [];

      for (const prop of allProps) {
        const apiDefaultProp = apiDocReader.getDefaultValueOf(component, prop);
        const projectDefaultProp = projectReader.getDefaultValueOf(component, prop);
        const problem = compareDefaultValues(apiDefaultProp, projectDefaultProp);
        if (problem) {
          missingDefaultProps.push(`Component "${component}", prop "${prop}": ${problem}`);
        }
      }

      expect(missingDefaultProps).toEqual([]);
    });

    test.each(storybookReader.getPublicComponentNames())(
      'if %s has default props in Storybook, it should also have them in the project',
      component => {
        const allProps = storybookReader.getRechartsPropsOf(component);
        const missingDefaultProps: string[] = [];

        for (const prop of allProps) {
          const storybookDefaultProp = storybookReader.getDefaultValueOf(component, prop);
          const projectDefaultProp = projectReader.getDefaultValueOf(component, prop);
          const problem = compareDefaultValues(
            /*
             * Storybook types demand that all default values are strings.
             * https://storybook.js.org/docs/api/arg-types#tabledefaultvalue
             * This however causes problems because `'false'` (string) is indeed very different from `false` (boolean).
             * So here let's make sure to compare the actual values,
             * even though it goes against Storybook's type definition.
             */
            storybookDefaultProp,
            projectDefaultProp,
          );
          if (problem) {
            missingDefaultProps.push(`Component "${component}", prop "${prop}": ${problem}`);
          }
        }

        expect(missingDefaultProps).toEqual([]);
      },
    );

    test.each(projectReader.getPublicComponentNames())(
      'if a %s prop is documented with a @default tag, it should match the actual default prop in the project',
      component => {
        const result: Array<string> = [];

        const allProps = projectReader.getRechartsPropsOf(component);
        for (const prop of allProps) {
          const propMeta = projectReader.getPropMeta(component, prop);
          const problems = propMeta
            .map(meta => {
              /*
               * Because everything coming out of the JSDoc is a string,
               * we need to convert the actual default value to string for comparison.
               */
              return compareDefaultValues(
                meta.defaultValueFromJSDoc,
                stringifyDefaultValue(meta.defaultValueFromObject),
              );
            })
            .filter(isNotNil)
            .map(description => `Component "${component}", prop "${prop}": ${description}`);
          if (problems) {
            result.push(...problems);
          }
        }

        expect(result).toEqual([]);
      },
    );
  });

  describe('comment/documentation consistency', () => {
    /**
     * Check if two comments are similar enough.
     * Returns true if both are empty/null, or if normalized texts match.
     */
    function areCommentsSimilar(comment1: string | undefined, comment2: string | undefined): boolean {
      const norm1 = normalizeText(comment1);
      const norm2 = normalizeText(comment2);

      // Both empty is considered similar
      if (norm1 === '' && norm2 === '') {
        return true;
      }

      // If one is empty and the other is not, they're different
      if (norm1 === '' || norm2 === '') {
        return false;
      }

      return norm1 === norm2;
    }

    test.each(
      apiDocReader
        .getPublicComponentNames()
        /*
         * Filter out components that are auto-generated because those are guaranteed to match
         */
        .filter(name => !OMNIDOC_AUTOMATED_API_DOCS_COMPONENTS.includes(name))
        /*
         * Filter out excluded components
         */
        .filter(name => !componentsExcludedFromOmnidoc.includes(name)),
    )('if %s has comments in API docs, they should match the project comments', component => {
      const allProps = apiDocReader.getAllPropsOf(component);

      const inconsistentComments: string[] = [];

      for (const prop of allProps) {
        const apiComment = apiDocReader.getCommentOf(component, prop);
        const projectComment = projectReader.getCommentOf(component, prop);

        // Skip if both are null/empty - that's consistent
        if (!apiComment && !projectComment) {
          continue;
        }

        const difference = coloredDiff(apiComment, projectComment);

        if (difference) {
          inconsistentComments.push(`Component "${component}", prop "${prop}" diff:\n${difference}`);
        }
      }

      expect(inconsistentComments).toEqual([]);
    });

    /**
     * This list is temporary - these components have known inconsistencies,
     * and we are fixing them. This list will shrink over time as we fix the comments one component at a time.
     */
    const componentsWithInconsistentCommentsInStorybook = [
      'CartesianAxis',
      'PolarGrid',
      'PolarRadiusAxis',
      'Polygon',
      'Radar',
      'RadarChart',
      'RadialBar',
      'RadialBarChart',
      'Rectangle',
      'ReferenceArea',
      'ReferenceDot',
      'ReferenceLine',
      'Sankey',
      'Scatter',
      'Sector',
      'Text',
      'Tooltip',
      'Trapezoid',
      'Treemap',
      'XAxis',
      'YAxis',
      'ZAxis',
    ];

    test.each(
      storybookReader
        .getPublicComponentNames()
        .filter(name => !STORYBOOK_AUTOMATED_ARG_COMPONENTS.includes(name))
        .filter(name => !componentsWithInconsistentCommentsInStorybook.includes(name)),
    )('if %s has comments in Storybook, they should match the project comments', component => {
      const allProps = storybookReader.getRechartsPropsOf(component);
      const inconsistentComments: string[] = [];

      for (const prop of allProps) {
        const storybookComment = storybookReader.getCommentOf(component, prop);
        const projectComment = projectReader.getCommentOf(component, prop);

        // Skip if both are null/empty - that's consistent
        if (!storybookComment && !projectComment) {
          continue;
        }

        if (!areCommentsSimilar(storybookComment, projectComment)) {
          inconsistentComments.push(
            `Component "${component}", prop "${prop}":\n` +
              `  Storybook: ${storybookComment || '(none)'}\n` +
              `  Project:   ${projectComment || '(none)'}`,
          );
        }
      }

      expect(inconsistentComments).toEqual([]);
    });

    /**
     * This list is temporary - these components have known inconsistencies,
     * and we are fixing them. This list will shrink over time as we fix the comments one component at a time.
     */
    const componentsWithInconsistentCommentsInApiDocAndStorybook = [
      'Area',
      'AreaChart',
      'Bar',
      'BarChart',
      'Brush',
      'CartesianGrid',
      'Cell',
      'ComposedChart',
      'Curve',
      'Dot',
      'Funnel',
      'FunnelChart',
      'Label',
      'LabelList',
      'Legend',
      'Line',
      'LineChart',
      'Pie',
      'PieChart',
      'PolarAngleAxis',
      'PolarGrid',
      'PolarRadiusAxis',
      'Polygon',
      'Radar',
      'RadarChart',
      'RadialBar',
      'RadialBarChart',
      'Rectangle',
      'ReferenceArea',
      'ReferenceDot',
      'ReferenceLine',
      'Sankey',
      'Scatter',
      'ScatterChart',
      'Sector',
      'Text',
      'Tooltip',
      'Trapezoid',
      'Treemap',
      'XAxis',
      'YAxis',
      'ZAxis',
    ];

    test.each(
      apiDocReader
        .getPublicComponentNames()
        /*
         * Filter out components that are auto-generated because those are guaranteed to match
         */
        .filter(name => !OMNIDOC_AUTOMATED_API_DOCS_COMPONENTS.includes(name))
        .filter(name => !componentsExcludedFromOmnidoc.includes(name))
        .filter(name => !componentsWithInconsistentCommentsInApiDocAndStorybook.includes(name)),
    )('if %s has comments in both API docs and Storybook, they should match', component => {
      const apiProps = new Set(apiDocReader.getRechartsPropsOf(component));
      const storybookProps = new Set(storybookReader.getRechartsPropsOf(component));

      // Find common props
      const commonProps = Array.from(apiProps).filter(prop => storybookProps.has(prop));
      const inconsistentComments: string[] = [];

      for (const prop of commonProps) {
        const apiComment = apiDocReader.getCommentOf(component, prop);
        const storybookComment = storybookReader.getCommentOf(component, prop);

        // Skip if both are null/empty - that's consistent
        if (!apiComment && !storybookComment) {
          continue;
        }

        if (!areCommentsSimilar(apiComment, storybookComment)) {
          inconsistentComments.push(
            `Component "${component}", prop "${prop}":\n` +
              `  API doc:   ${apiComment || '(none)'}\n` +
              `  Storybook: ${storybookComment || '(none)'}`,
          );
        }
      }

      expect(inconsistentComments).toEqual([]);
    });
  });

  describe.todo('the type definition of each prop should be consistent between API docs, Storybook, and the project');
});
