import BarChartRangeExampleComponent from '../../../www/src/docs/exampleComponents/BarChart/BarChartRangeExample';
import TinyBarChartComponent from '../../../www/src/docs/exampleComponents/BarChart/TinyBarChart';
import SimpleBarChartComponent from '../../../www/src/docs/exampleComponents/BarChart/SimpleBarChart';
import StackedBarChartComponent from '../../../www/src/docs/exampleComponents/BarChart/StackedBarChart';
import MixBarChartComponent from '../../../www/src/docs/exampleComponents/BarChart/MixBarChart';
import CustomShapeBarChartComponent from '../../../www/src/docs/exampleComponents/BarChart/CustomShapeBarChart';
import PositiveAndNegativeBarChartComponent from '../../../www/src/docs/exampleComponents/BarChart/PositiveAndNegativeBarChart';
import BrushBarChartComponent from '../../../www/src/docs/exampleComponents/BarChart/BrushBarChart';
import BarChartWithCustomizedEventComponent from '../../../www/src/docs/exampleComponents/BarChart/BarChartWithCustomizedEvent';
import BarChartWithMinHeightComponent from '../../../www/src/docs/exampleComponents/BarChart/BarChartWithMinHeight';
import BarChartStackedBySignComponent from '../../../www/src/docs/exampleComponents/BarChart/BarChartStackedBySign';
import BiaxialBarChartComponent from '../../../www/src/docs/exampleComponents/BarChart/BiaxialBarChart';
import BarChartHasBackgroundComponent from '../../../www/src/docs/exampleComponents/BarChart/BarChartHasBackground';
import BarChartWithMultiXAxisComponent from '../../../www/src/docs/exampleComponents/BarChart/BarChartWithMultiXAxis';
import BarChartNavExampleComponent from '../../../www/src/docs/exampleComponents/BarChart/BarChartNavExample';
import RangedStackedBarChartComponent from '../../../www/src/docs/exampleComponents/BarChart/RangedStackedBarChart';
import PopulationPyramidExampleComponent from '../../../www/src/docs/exampleComponents/BarChart/PopulationPyramidExample';
import TimelineExampleComponent from '../../../www/src/docs/exampleComponents/BarChart/TimelineExample';
import CandlestickExampleComponent from '../../../www/src/docs/exampleComponents/BarChart/CandlestickExample';
import BoxPlotExampleComponent from '../../../www/src/docs/exampleComponents/BarChart/BoxPlotExample';
import AnimatedBarWidthExampleComponent from '../../../www/src/docs/exampleComponents/BarChart/AnimatedBarWidthExample';
import { themedStory } from './StoryTheme';

export const CandlestickExample = themedStory(CandlestickExampleComponent);
export const BoxPlotExample = themedStory(BoxPlotExampleComponent);
export const TimelineExample = themedStory(TimelineExampleComponent);
export const PopulationPyramidExample = themedStory(PopulationPyramidExampleComponent);
export const BarChartNavExample = themedStory(BarChartNavExampleComponent);
export const BarChartWithMultiXAxis = themedStory(BarChartWithMultiXAxisComponent);
export const BarChartHasBackground = themedStory(BarChartHasBackgroundComponent);
export const BiaxialBarChart = themedStory(BiaxialBarChartComponent);
export const BarChartStackedBySign = themedStory(BarChartStackedBySignComponent);
export const BarChartWithMinHeight = themedStory(BarChartWithMinHeightComponent);
export const BarChartWithCustomizedEvent = themedStory(BarChartWithCustomizedEventComponent);
export const BrushBarChart = themedStory(BrushBarChartComponent);
export const PositiveAndNegativeBarChart = themedStory(PositiveAndNegativeBarChartComponent);
export const CustomShapeBarChart = themedStory(CustomShapeBarChartComponent);
export const MixBarChart = themedStory(MixBarChartComponent);
export const StackedBarChart = themedStory(StackedBarChartComponent);
export const SimpleBarChart = themedStory(SimpleBarChartComponent);
export const TinyBarChart = themedStory(TinyBarChartComponent);
export const BarChartRangeExample = themedStory(BarChartRangeExampleComponent);
export const RangedStackedBarChart = themedStory(RangedStackedBarChartComponent);
export const AnimatedBarWidthExample = themedStory(AnimatedBarWidthExampleComponent);
