import BarChartRangeExampleComponent from '../../../www/src/docs/exampleComponents/BarChart/BarChartRangeExample';
import TinyBarChartComponent from '../../../www/src/docs/exampleComponents/BarChart/TinyBarChart';
import SimpleBarChartComponent from '../../../www/src/docs/exampleComponents/BarChart/SimpleBarChart';
import StackedBarChartComponent from '../../../www/src/docs/exampleComponents/BarChart/StackedBarChart';
import MixBarChartComponent from '../../../www/src/docs/exampleComponents/BarChart/MixBarChart';
import CustomShapeBarChartComponent from '../../../www/src/docs/exampleComponents/BarChart/CustomShapeBarChart';
import PositiveAndNegativeBarChartComponent from '../../../www/src/docs/exampleComponents/BarChart/PositiveAndNegativeBarChart';
import BrushBarChartComponent from '../../../www/src/docs/exampleComponents/BarChart/BrushBarChart';
import BarChartWithCustomizedEventComponent from '../../../www/src/docs/exampleComponents/BarChart/BarChartWithCustomizedEvent';
import BarChartWithMinHeightComponent from '../../../www/src/docs/exampleComponents/BarChart/BarChartWithMinHeight';
import BarChartStackedBySignComponent from '../../../www/src/docs/exampleComponents/BarChart/BarChartStackedBySign';
import BiaxialBarChartComponent from '../../../www/src/docs/exampleComponents/BarChart/BiaxialBarChart';
import BarChartHasBackgroundComponent from '../../../www/src/docs/exampleComponents/BarChart/BarChartHasBackground';
import BarChartWithMultiXAxisComponent from '../../../www/src/docs/exampleComponents/BarChart/BarChartWithMultiXAxis';
import BarChartNavExampleComponent from '../../../www/src/docs/exampleComponents/BarChart/BarChartNavExample';
import RangedStackedBarChartComponent from '../../../www/src/docs/exampleComponents/BarChart/RangedStackedBarChart';
import PopulationPyramidExampleComponent from '../../../www/src/docs/exampleComponents/BarChart/PopulationPyramidExample';
import TimelineExampleComponent from '../../../www/src/docs/exampleComponents/BarChart/TimelineExample';
import CandlestickExampleComponent from '../../../www/src/docs/exampleComponents/BarChart/CandlestickExample';
import BoxPlotExampleComponent from '../../../www/src/docs/exampleComponents/BarChart/BoxPlotExample';
import AnimatedBarWidthExampleComponent from '../../../www/src/docs/exampleComponents/BarChart/AnimatedBarWidthExample';

export const CandlestickExample = CandlestickExampleComponent;
export const BoxPlotExample = BoxPlotExampleComponent;
export const TimelineExample = TimelineExampleComponent;
export const PopulationPyramidExample = PopulationPyramidExampleComponent;
export const BarChartNavExample = BarChartNavExampleComponent;
export const BarChartWithMultiXAxis = BarChartWithMultiXAxisComponent;
export const BarChartHasBackground = BarChartHasBackgroundComponent;
export const BiaxialBarChart = BiaxialBarChartComponent;
export const BarChartStackedBySign = BarChartStackedBySignComponent;
export const BarChartWithMinHeight = BarChartWithMinHeightComponent;
export const BarChartWithCustomizedEvent = BarChartWithCustomizedEventComponent;
export const BrushBarChart = BrushBarChartComponent;
export const PositiveAndNegativeBarChart = PositiveAndNegativeBarChartComponent;
export const CustomShapeBarChart = CustomShapeBarChartComponent;
export const MixBarChart = MixBarChartComponent;
export const StackedBarChart = StackedBarChartComponent;
export const SimpleBarChart = SimpleBarChartComponent;
export const TinyBarChart = TinyBarChartComponent;
export const BarChartRangeExample = BarChartRangeExampleComponent;
export const RangedStackedBarChart = RangedStackedBarChartComponent;
export const AnimatedBarWidthExample = AnimatedBarWidthExampleComponent;
