import { ApiDoc } from './types';

export const ZAxisAPI: ApiDoc = {
  name: 'ZAxis',
  props: [
    {
      name: 'dataKey',
      type: 'string | number | Function',
      isOptional: true,
      desc: {
        'en-US': (
          <section>
            <p>Decides how to extract the value of this Axis from the data:</p>
            <ul>
              <li>
                <code>string</code>: the name of the field in the data object;
              </li>
              <li>
                <code>number</code>: the index of the field in the data;
              </li>
              <li>
                <code>function</code>: a function that receives the data object and returns the value of this Axis.
              </li>
            </ul>
            <p>If undefined, it will reuse the dataKey of graphical items.</p>
          </section>
        ),
      },
    },
    {
      name: 'domain',
      type: 'Array<readonly string> | Array<readonly number> | readonly [AxisDomainItem, AxisDomainItem] | Function',
      isOptional: true,
      desc: {
        'en-US': (
          <section>
            <p>Specify the domain of axis when the axis is a number axis.</p>
            <p>If undefined, then the domain is calculated based on the data and dataKeys.</p>
            <p>The length of domain should be 2, and we will validate the values in domain.</p>
            <p>
              Each element in the array can be a number, &#39;auto&#39;, &#39;dataMin&#39;, &#39;dataMax&#39;, a string
              like &#39;dataMin - 20&#39;, &#39;dataMax + 100&#39;, or a function that accepts a single argument and
              returns a number.
            </p>
            <p>
              If any element of domain is set to be &#39;auto&#39;, comprehensible scale ticks will be calculated, and
              the final domain of axis is generated by the ticks. If a function, receives &#39;[dataMin, dataMax]&#39;,
              and must return a computed domain as &#39;[min, max]&#39;.
            </p>
          </section>
        ),
      },
      format: [
        "<ZAxis type=\"number\" domain={['dataMin', 'dataMax']} />",
        '<ZAxis type="number" domain={[0, \'dataMax\']} />',
        "<ZAxis type=\"number\" domain={['auto', 'auto']} />",
        '<ZAxis type="number" domain={[0, \'dataMax + 1000\']} />',
        "<ZAxis type=\"number\" domain={['dataMin - 100', 'dataMax + 100']} />",
        '<ZAxis type="number" domain={[dataMin => (0 - Math.abs(dataMin)), dataMax => (dataMax * 2)]} />',
        '<ZAxis type="number" domain={([dataMin, dataMax]) => { const absMax = Math.max(Math.abs(dataMin), Math.abs(dataMax)); return [-absMax, absMax]; }} />',
        '<ZAxis type="number" domain={[0, 100]} allowDataOverflow />',
      ],
    },
    {
      name: 'name',
      type: 'string',
      isOptional: true,
      desc: {
        'en-US': (
          <section>
            <p>
              The name of data. This option will be used in tooltip. If no value was set to this option, the value of
              dataKey will be used alternatively.
            </p>
          </section>
        ),
      },
    },
    {
      name: 'range',
      type: 'AxisRange',
      isOptional: true,
      desc: {
        'en-US': (
          <section>
            <p>The range of axis. Unlike other axes, the range of z-axis is not informed by chart dimensions.</p>
          </section>
        ),
      },
      defaultVal: [64, 64],
    },
    {
      name: 'scale',
      type: '(union of 20 variants)',
      isOptional: true,
      desc: {
        'en-US': (
          <section>
            <p>
              Scale function determines how data values are mapped to visual values. In other words, decided the mapping
              between data domain and coordinate range.
            </p>
            <p>
              If undefined, or &#39;auto&#39;, the scale function is created internally according to the type of axis
              and data.
            </p>
            <p>
              You can define a custom scale, either as a string shortcut to a d3 scale, or as a complete scale
              definition object.
            </p>
          </section>
        ),
      },
      defaultVal: 'auto',
      format: [
        '<ZAxis scale="log" />',
        "import { scaleLog } from 'd3-scale';\nconst scale = scaleLog().base(Math.E);\n<ZAxis scale={scale} />",
      ],
    },
    {
      name: 'type',
      type: '"number" | "category"',
      isOptional: true,
      desc: {
        'en-US': (
          <section>
            <p>
              The type of axis. Numeric axis operates in a continuous range of numbers. Category axis operates in a
              discrete set of categories.
            </p>
          </section>
        ),
      },
      defaultVal: 'number',
    },
    {
      name: 'unit',
      type: 'string',
      isOptional: true,
      desc: {
        'en-US': (
          <section>
            <p>The unit of data. This option will be used in tooltip.</p>
          </section>
        ),
      },
    },
    {
      name: 'zAxisId',
      type: 'string | number',
      isOptional: true,
      desc: {
        'en-US': (
          <section>
            <p>The unique id of z-axis.</p>
          </section>
        ),
      },
      defaultVal: 0,
    },
  ],
  desc: {
    'en-US': (
      <section>
        <p>
          Virtual axis, does not render anything itself. Has no ticks, grid lines, or labels. Useful for dynamically
          setting Scatter point size, based on data.
        </p>
      </section>
    ),
  },
  parentComponents: ['AreaChart', 'BarChart', 'ComposedChart', 'FunnelChart', 'LineChart', 'ScatterChart'],
};
