import React from 'react';
import { PolarAngleAxis, RadialBarChart } from '../../../../src';
import { EventHandlers } from '../props/EventHandlers';
import { pageData } from '../../data';
import { getStoryArgsFromArgsTypesObject } from '../props/utils';
import { StorybookArgs } from '../../../StorybookArgs';

const GeneralProps: StorybookArgs = {
  type: {
    description: 'The type of axis.',
    options: ['number', 'category'],
    control: 'radio',
    table: { type: { summary: 'number | category' }, defaultValue: 'category', category: 'General' },
  },
  allowDuplicatedCategory: {
    description: 'Allow the axis that has duplicated category or not when the type of axis is "category".',
    table: { type: { summary: 'boolean' }, category: 'General' },
    defaultValue: true,
  },
  domain: {
    description: `Specify the domain of radius in a polar chart.
      And the length should be 2. And each element in the array
      can be a number, 'auto', 'dataMin' or 'dataMax'.
      If any element of domain is set to be 'auto',
      comprehensible scale ticks will be calculated,
      and the final domain of axis is generated by the ticks.
      If a function, receives '[dataMin, dataMax]', and must return a computed domain as '[min, max]'.s`,
    table: { type: { summary: 'Array | Function' }, category: 'General' },
    defaultValue: [0, 'auto'],
  },
  reversed: {
    description: 'If set to true, the ticks of this axis are reversed.',
    table: { type: { summary: 'boolean' }, defaultValue: false, category: 'General' },
  },
  orientation: {
    description: 'The orientation of axis text.',
    table: { type: { summary: 'inner | outer' }, defaultValue: 'outer', category: 'General' },
  },
  axisLine: {
    description: `If false set, axis line will not be drawn.
    If true set, axis line will be drawn which have the props calculated internally.
    If object set, axis line will be drawn which have the props merged by the internal calculated props and the option.`,
    control: 'boolean',
    table: { type: { summary: 'boolean | Object' }, defaultValue: true, category: 'General' },
  },
  tick: {
    description: `If false set, ticks will not be drawn. If true set,
    ticks will be drawn which have the props calculated internally.
    If object set, ticks will be drawn which have the props mergered by the internal calculated props and the option.
    If ReactElement set, the option can be the custom tick element. If set a function, the function will be called to render customized ticks.`,
    control: 'boolean',
    table: { type: { summary: 'boolean | Object | Element | Function' }, defaultValue: true, category: 'General' },
  },
  tickFormatter: {
    description: 'The function to formatting tick.',
    table: { type: { summary: 'number' }, category: 'General' },
  },
  scale: {
    description: 'The function to formatting tick.',
    options: ['auto', 'linear', 'pow', 'sqrt', 'log', 'identity', 'point'],
    control: 'select',
    table: {
      type: {
        summary: `auto | linear | pow | sqrt | log | identity
          | time | band | point | ordinal | quantile | quantize | utc | sequential | threshold | Function`,
      },
      category: 'General',
      defaultValue: 'auto',
    },
  },
};

export default {
  argTypes: {
    ...GeneralProps,
    ...EventHandlers,
  },
  component: PolarAngleAxis,
};
const [surfaceWidth, surfaceHeight] = [600, 300];

export const API = {
  render: (args: Record<string, any>) => {
    return (
      <RadialBarChart width={surfaceWidth} height={surfaceHeight} data={pageData}>
        <PolarAngleAxis {...args} />
      </RadialBarChart>
    );
  },
  args: {
    ...getStoryArgsFromArgsTypesObject(GeneralProps),
    axisLineType: 'polygon',
    stroke: 'green',
    dataKey: 'uv',
    type: 'number',
  },
};
