import * as React from 'react';
import { describe, it, expect } from 'vitest';
import { createSelectorTestCase } from '../helper/createSelectorTestCase';
import { Bar, BarChart, BarStack } from '../../src';
import { PageData } from '../_data';
import { useBarStackClipPathUrl, useStackId } from '../../src/cartesian/BarStack';
import { expectLastCalledWith } from '../helper/expectLastCalledWith';

describe('BarStack', () => {
  describe('when stackId is provided explicitly', () => {
    const renderTestCase = createSelectorTestCase(({ children }) => (
      <BarChart width={100} height={100} data={PageData}>
        <BarStack stackId="custom-stack" radius={50}>
          <Bar dataKey="uv" />
          <Bar dataKey="pv" />
          {children}
        </BarStack>
      </BarChart>
    ));

    it('should expose stackId prop via a hook', () => {
      const { spy } = renderTestCase(() => useStackId(undefined));
      expectLastCalledWith(spy, 'custom-stack');
    });

    it('should prefer context stackId over child', () => {
      const { spy } = renderTestCase(() => useStackId('child-stack'));
      expectLastCalledWith(spy, 'custom-stack');
    });

    it('should return clip path URL from a hook', () => {
      const { spy } = renderTestCase(() => useBarStackClipPathUrl(7));
      expectLastCalledWith(spy, 'url(#recharts-bar-stack-clip-path-custom-stack-7)');
    });
  });

  describe('when stackId is autogenerated', () => {
    const renderTestCase = createSelectorTestCase(({ children }) => (
      <BarChart width={100} height={100} data={PageData}>
        <BarStack radius={50}>
          <Bar dataKey="uv" />
          <Bar dataKey="pv" />
          {children}
        </BarStack>
      </BarChart>
    ));

    it('should expose stackId prop via a hook', () => {
      const { spy } = renderTestCase(() => useStackId(undefined));
      const expectedStackIdPrefix = 'recharts-bar-stack-';
      expectLastCalledWith(spy, expect.stringContaining(expectedStackIdPrefix));
    });

    it('should prefer context stackId over child', () => {
      const { spy } = renderTestCase(() => useStackId('child-stack'));
      const expectedStackIdPrefix = 'recharts-bar-stack-';
      expectLastCalledWith(spy, expect.stringContaining(expectedStackIdPrefix));
    });

    it('should return clip path URL from a hook', () => {
      const { spy } = renderTestCase(() => useBarStackClipPathUrl(7));
      const expectedStackIdPrefix = 'url(#recharts-bar-stack-clip-path-';
      expectLastCalledWith(spy, expect.stringContaining(expectedStackIdPrefix));
    });
  });

  describe('in chart without BarStack', () => {
    const renderTestCase = createSelectorTestCase(({ children }) => (
      <BarChart width={100} height={100} data={PageData}>
        <Bar dataKey="uv" />
        <Bar dataKey="pv" />
        {children}
      </BarChart>
    ));

    it('should return undefined stackId from a hook', () => {
      const { spy } = renderTestCase(() => useStackId(undefined));
      expectLastCalledWith(spy, undefined);
    });

    it('should return child stackId from a hook', () => {
      const { spy } = renderTestCase(() => useStackId('child-stack'));
      expectLastCalledWith(spy, 'child-stack');
    });

    it('should return undefined clip path URL from a hook', () => {
      const { spy } = renderTestCase(() => useBarStackClipPathUrl(7));
      expectLastCalledWith(spy, undefined);
    });
  });
});
