export const component = 'CartesianAxis' as const;
export const expectedInBundle = [
  'CartesianAxis',
  'BarChart',
  'RadialBarChart',
  'Line',
  'Area',
  'Bar',
  'Scatter',
  'XAxis',
  'YAxis',
  'Brush',
  'ReferenceLine',
  'ReferenceDot',
  'ReferenceArea',
  'CartesianGrid',
  'Funnel',
  'Pie',
  'Radar',
  'RadialBar',
  'PolarGrid',
  'PolarAngleAxis',
  'PolarRadiusAxis',
] as const;
