export const component = 'RadialBar' as const;
export const expectedInBundle = [
  'RadialBar',
  'LineChart',
  'BarChart',
  'AreaChart',
  'ScatterChart',
  'RadialBarChart',
  'ComposedChart',
  'Treemap',
  'Sankey',
  'Line',
  'Area',
  'Bar',
  'BarStack',
  'Scatter',
  'XAxis',
  'YAxis',
  'ZAxis',
  'ErrorBar',
  'Brush',
  'ReferenceLine',
  'ReferenceDot',
  'ReferenceArea',
  'CartesianAxis',
  'CartesianGrid',
  'Funnel',
  'Pie',
  'Radar',
  'PolarGrid',
  'PolarAngleAxis',
  'PolarRadiusAxis',
] as const;
