export const expectedInBundle = [
  'Area',
  'Curve',
  'DefaultZIndexes',
  'Dot',
  'getNiceTickValues',
  'Global',
  'interpolate',
  'Label',
  'LabelList',
  'Layer',
  'Text',
  'useActiveTooltipDataPoints',
  'usePlotArea',
  'ZIndexLayer',
  'useChartLayout',
  'useCartesianChartLayout',
] as const;
