export const expectedInBundle = [
  'Cell',
  'DefaultZIndexes',
  'Funnel',
  'getNiceTickValues',
  'Global',
  'interpolate',
  'Label',
  'LabelList',
  'Layer',
  'matchAppend',
  'matchByIndex',
  'Text',
  'Trapezoid',
  'usePlotArea',
  'ZIndexLayer',
  'useChartLayout',
] as const;
