export const expectedInBundle = [
  'Curve',
  'DefaultZIndexes',
  'Dot',
  'getNiceTickValues',
  'Global',
  'interpolate',
  'Label',
  'LabelList',
  'Layer',
  'Line',
  'Rectangle',
  'Sector',
  'Symbols',
  'Text',
  'Trapezoid',
  'useActiveTooltipDataPoints',
  'usePlotArea',
  'ZIndexLayer',
  'useChartLayout',
] as const;
