export const expectedInBundle = [
  'Cell',
  'Curve',
  'DefaultZIndexes',
  'getNiceTickValues',
  'Global',
  'interpolate',
  'Label',
  'LabelList',
  'Layer',
  'matchAppend',
  'matchByIndex',
  'Scatter',
  'Symbols',
  'Text',
  'usePlotArea',
  'useChartLayout',
  'ZIndexLayer',
] as const;
