import { renderToString } from 'react-dom/server';
import { StaticRouter } from 'react-router';
import { routes } from './routes';
import { supportedLocales } from './locale';
import { getSiteRoutes } from './navigation.data';

export function render(url: string, template: string) {
  const appHtml = renderToString(<StaticRouter location={url}>{routes()}</StaticRouter>);

  return template.replace('<div id="app"></div>', `<div id="app">${appHtml}</div>`);
}

/*
 * Your IDE may flag this function as unused, but actually it is used by prerender.tsx.
 * It's imported dynamically from the autogenerated file so your IDE may not be able to discover that.
 */
// noinspection JSUnusedGlobalSymbols
export function getAllRoutes(): string[] {
  const allRoutes: string[] = ['/'];

  // Get base routes from getSiteRoutes (without locale prefix)
  const baseRoutes = getSiteRoutes();
  allRoutes.push(...baseRoutes);

  // Add routes with locale prefixes for all locales
  supportedLocales.forEach(locale => {
    allRoutes.push(`/${locale}`);
    baseRoutes.forEach(route => {
      allRoutes.push(`/${locale}${route}`);
    });
  });

  return allRoutes;
}
