export const apiComponents = [
  'AreaChart',
  'BarChart',
  'LineChart',
  'ComposedChart',
  'PieChart',
  'RadarChart',
  'RadialBarChart',
  'ScatterChart',
  'FunnelChart',
  'Treemap',
  'SankeyChart',
  'ResponsiveContainer',
  'Legend',
  'Tooltip',
  'Cell',
  'Text',
  'Label',
  'LabelList',
  'Customized',
  'Area',
  'Bar',
  'Line',
  'Scatter',
  'XAxis',
  'YAxis',
  'ZAxis',
  'Brush',
  'CartesianAxis',
  'CartesianGrid',
  'ReferenceLine',
  'ReferenceDot',
  'ReferenceArea',
  'ErrorBar',
  'Funnel',
  'Pie',
  'Radar',
  'RadialBar',
  'PolarAngleAxis',
  'PolarGrid',
  'PolarRadiusAxis',
  'Cross',
  'Curve',
  'Dot',
  'Polygon',
  'Rectangle',
  'Sector',
  'Trapezoid',
];

export const exampleComponents = [
  'TinyLineChart',
  'SimpleLineChart',
  'DashedLineChart',
  'VerticalLineChart',
  'BiaxialLineChart',
  'VerticalLineChartWithSpecifiedDomain',
  'LineChartConnectNulls',
  'LineChartWithXAxisPadding',
  'LineChartWithReferenceLines',
  'CustomizedDotLineChart',
  'CustomizedLabelLineChart',
  'SynchronizedLineChart',
  'HighlightAndZoomLineChart',
  'LineChartHasMultiSeries',
  'LineChartAxisInterval',
  'LineChartNegativeValuesWithReferenceLines',
  'SimpleAreaChart',
  'StackedAreaChart',
  'AreaChartConnectNulls',
  'CardinalAreaChart',
  'PercentAreaChart',
  'SynchronizedAreaChart',
  'TinyAreaChart',
  'AreaChartFillByValue',
  'TinyBarChart',
  'SimpleBarChart',
  'StackedBarChart',
  'MixBarChart',
  'CustomShapeBarChart',
  'PositiveAndNegativeBarChart',
  'BrushBarChart',
  'BarChartWithCustomizedEvent',
  'BarChartWithMinHeight',
  'BarChartStackedBySign',
  'BiaxialBarChart',
  'BarChartHasBackground',
  'BarChartWithMultiXAxis',
  'LineBarAreaComposedChart',
  'SameDataComposedChart',
  'VerticalComposedChart',
  'ComposedChartWithAxisLabels',
  'ScatterAndLineOfBestFit',
  'BandedChart',
  'SimpleScatterChart',
  'ThreeDimScatterChart',
  'JointLineScatterChart',
  'BubbleChart',
  'ScatterChartWithLabels',
  'MultipleYAxesScatterChart',
  'ScatterChartWithCells',
  'ScatterChartPerformance',
  'TwoLevelPieChart',
  'StraightAnglePieChart',
  'CustomActiveShapePieChart',
  'PieChartWithCustomizedLabel',
  'PieChartWithPaddingAngle',
  'PieChartWithNeedle',
  'PieChartInFlexbox',
  'PieChartInGrid',
  'SimpleRadarChart',
  'SpecifiedDomainRadarChart',
  'SimpleRadialBarChart',
  'SimpleTreemap',
  'CustomContentTreemap',
  'CustomContentOfTooltip',
  'LegendEffectOpacity',
  'AreaResponsiveContainer',
  'ComposedResponsiveContainer',
  'PieResponsiveContainer',
];

export const guidePages = ['installation', 'getting-started', 'customize', 'activeIndex', 'sizes'];

export function getAllUrls(): string[] {
  const locales = ['en-US', 'zh-CN'];
  const routes: Array<string> = [];

  locales.forEach(locale => {
    routes.push(`/${locale}/`);
    routes.push(`/${locale}/guide`);
    routes.push(`/${locale}/api`);
    routes.push(`/${locale}/examples`);
    routes.push(`/${locale}/storybook`);

    guidePages.forEach(slug => routes.push(`/${locale}/guide/${slug}`));
    apiComponents.forEach(slug => routes.push(`/${locale}/api/${slug}`));
    exampleComponents.forEach(slug => routes.push(`/${locale}/examples/${slug}`));
  });

  return routes;
}
