# this a dummy workflow to test debug github actions

name: Debug Actions

on:
  pull_request:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Debug Info
          run: |
            echo "Debugging GitHub Actions"
            echo "Current directory:"
            pwd
            echo "List files:"
            ls -la
            echo "Node.js version:"
            node -v || echo "Node.js is not installed"
            echo "NPM version:"
            npm -v || echo "NPM is not installed"
            echo "Environment Variables:"
            printenv
