name: PR Integration Tests

on:
  pull_request:
    branches:
      - 3.x

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mane Repo @ PR Commit
        uses: actions/checkout@v4
        with:
          path: 'recharts' # Checkout into a specific directory

      # 2. Checkout Integration Tests Code
      - name: Checkout Integration Tests
        uses: actions/checkout@v4
        with:
          repository: recharts/recharts-integ
          path: 'recharts-integ'

      # 3. Setup Node, Build & Pack Library
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your preferred Node.js version
          cache: 'npm'
          cache-dependency-path: 'recharts/package-lock.json' # Adjust if needed

      - name: Install Dependencies
        working-directory: ./recharts
        run: npm ci

      - name: Build
        working-directory: ./recharts
        run: npm run build

      - name: Pack
        id: pack_library
        working-directory: ./recharts
        run: |
          npm pack
          tgz_file=$(ls *.tgz)
          echo "Packed library file: $tgz_file"
          echo "tgz_filename=$tgz_file" >> $GITHUB_OUTPUT

      # 4. Run Integration Tests
      - name: Run Integration Tests
        working-directory: ./recharts-integ # Go into the checked-out tests directory
        run: ./run-test integrations-npm/ts-react18 ${{ steps.pack_library.outputs.tgz_filename }}
